--!strict

-- Pulse Deck Arena - Ability Configuration
-- Each ability defines its type, cooldown, and effect parameters

local AbilityConfig = {

	-- === MOBILITY ===

	phase_dash = {
		id = "phase_dash",
		displayName = "Phase Dash",
		heroId = "bolt_runner",
		description = "Dash forward with brief invulnerability.",
		cooldown = 9,
		kind = "Mobility",
		dashDistance = 38,
		invulnerabilitySeconds = 0.25,
		leaveTrail = true,
		trailColor = Color3.fromRGB(255, 222, 35),
		trailDuration = 0.5,
	},

	shadow_step = {
		id = "shadow_step",
		displayName = "Shadow Step",
		heroId = "reaper",
		description = "Teleport through shadows to a target location.",
		cooldown = 10,
		kind = "Mobility",
		dashDistance = 45,
		invulnerabilitySeconds = 0.35,
		stealthOnArrival = true,
		stealthDuration = 1.0,
		leaveTrail = true,
		trailColor = Color3.fromRGB(40, 40, 50),
		trailDuration = 0.6,
	},

	time_dilation = {
		id = "time_dilation",
		displayName = "Time Dilation",
		heroId = "chrono",
		description = "Slow down time around you for everyone but yourself.",
		cooldown = 30,
		kind = "Mobility",
		radius = 30,
		duration = 4,
		selfSpeedMultiplier = 1.4,
		enemySlowMultiplier = 0.4,
		effectColor = Color3.fromRGB(100, 150, 255),
	},

	overcharge = {
		id = "overcharge",
		displayName = "Overcharge",
		heroId = "nova",
		description = "Boost your speed and fire rate temporarily.",
		cooldown = 18,
		kind = "Mobility",
		duration = 5,
		speedMultiplier = 1.35,
		fireRateMultiplier = 1.3,
		energyColor = Color3.fromRGB(255, 100, 200),
	},

	-- === DEFENSIVE ===

	shield_dome = {
		id = "shield_dome",
		displayName = "Shield Dome",
		heroId = "iron_bulwark",
		description = "Project a dome shield that absorbs damage.",
		cooldown = 17,
		kind = "DefensiveDeployable",
		duration = 6,
		radius = 14,
		damageReduction = 0.4,
		domeHealth = 300,
		healInsideAlly = 5,
		healTickInterval = 0.5,
		color = Color3.fromRGB(80, 160, 255),
	},

	fortify = {
		id = "fortify",
		displayName = "Fortify",
		heroId = "bastion",
		description = "Enter a fortified stance, greatly reducing damage taken.",
		cooldown = 16,
		kind = "DefensiveSelf",
		duration = 5,
		damageReduction = 0.6,
		cannotMove = true,
		canFireWhileActive = true,
		effectColor = Color3.fromRGB(200, 100, 50),
	},

	-- === OFFENSIVE ===

	tracker_mark = {
		id = "tracker_mark",
		displayName = "Tracker Mark",
		heroId = "vesper_scope",
		description = "Mark an enemy through walls, increasing damage taken.",
		cooldown = 14,
		kind = "MarkRay",
		duration = 8,
		range = 700,
		vesperDamageMultiplier = 1.2,
		allDamageMultiplier = 1.15,
		revealStealth = true,
	},

	cluster_charge = {
		id = "cluster_charge",
		displayName = "Cluster Charge",
		heroId = "fuse_jack",
		description = "Throw a grenade that splits into mini-explosions.",
		cooldown = 15,
		kind = "GrenadeCluster",
		fuseSeconds = 1.4,
		throwSpeed = 120,
		mainDamage = 50,
		mainRadius = 18,
		miniCount = 5,
		miniDamage = 20,
		miniRadius = 9,
		miniSpread = 12,
		objectiveMultiplier = 1.3,
	},

	blink_swap = {
		id = "blink_swap",
		displayName = "Blink Swap",
		heroId = "glitch_byte",
		description = "Teleport behind an enemy, leaving a decoy.",
		cooldown = 12,
		kind = "Teleport",
		teleportDistance = 35,
		targetBlinkRange = 55,
		behindTargetOffset = 8,
		decoyDuration = 1.5,
		decoyExplodes = true,
		decoyDamage = 30,
		decoyRadius = 8,
	},

	nova_burst = {
		id = "nova_burst",
		displayName = "Nova Burst",
		heroId = "nova",
		description = "Release a pulse of energy that damages and knocks back enemies.",
		cooldown = 14,
		kind = "AreaBurst",
		radius = 18,
		damage = 55,
		knockbackForce = 50,
		energyCost = 60,
		color = Color3.fromRGB(255, 80, 180),
	},

	-- === SUPPORT ===

	heal_pulse = {
		id = "heal_pulse",
		displayName = "Heal Pulse",
		heroId = "patch_flux",
		description = "Heal nearby allies and damage enemies in the area.",
		cooldown = 12,
		kind = "AreaHealDamage",
		radius = 22,
		allyHeal = 50,
		enemyDamage = 18,
		healOverTime = 3,
		healOverTimeDuration = 3,
	},

	rejuvenation_field = {
		id = "rejuvenation_field",
		displayName = "Rejuvenation Field",
		heroId = "nova",
		description = "Deploy a healing field that regenerates allies over time.",
		cooldown = 20,
		kind = "AreaHealDeployable",
		duration = 8,
		radius = 16,
		healPerSecond = 8,
		maxHealPerAlly = 60,
		color = Color3.fromRGB(100, 255, 150),
	},

	-- === UTILITY ===

	mini_sentry = {
		id = "mini_sentry",
		displayName = "Mini Sentry",
		heroId = "terra_pin",
		description = "Deploy a turret that fires at enemies.",
		cooldown = 20,
		kind = "SentryDeployable",
		duration = 16,
		health = 130,
		range = 100,
		damage = 10,
		fireInterval = 0.3,
		bulletSpeed = 500,
		maxTargets = 1,
	},

	smart_mine = {
		id = "smart_mine",
		displayName = "Smart Mine",
		heroId = "terra_pin",
		description = "Place a proximity mine that tracks nearby enemies.",
		cooldown = 18,
		kind = "MineDeployable",
		duration = 30,
		health = 30,
		range = 50,
		damage = 60,
		splashRadius = 10,
		maxMines = 3,
		armTime = 1.0,
	},

	slow_field = {
		id = "slow_field",
		displayName = "Slow Field",
		heroId = "wisp_ion",
		description = "Create a field that slows enemies and damages over time.",
		cooldown = 16,
		kind = "AreaControl",
		duration = 6,
		radius = 18,
		targetRange = 100,
		enemySlowMultiplier = 0.6,
		damagePerSecond = 6,
		allyReloadSpeedMultiplier = 1.15,
		groundEffect = true,
	},

	gravity_well = {
		id = "gravity_well",
		displayName = "Gravity Well",
		heroId = "reaper",
		description = "Pull enemies toward a central point.",
		cooldown = 18,
		kind = "AreaControl",
		radius = 16,
		duration = 4,
		pullStrength = 12,
		damagePerSecond = 10,
		color = Color3.fromRGB(180, 50, 255),
	},

	energy_shield = {
		id = "energy_shield",
		displayName = "Energy Shield",
		heroId = "bastion",
		description = "Project a forward energy barrier that blocks shots.",
		cooldown = 14,
		kind = "DirectionalShield",
		duration = 4,
		width = 10,
		height = 6,
		maxHealth = 200,
		damageAbsorption = 0.5,
		reflectChance = 0.15,
		color = Color3.fromRGB(255, 180, 50),
	},

	ultimate_ability = {
		id = "ultimate_ability",
		displayName = "ULTIMATE",
		heroId = "bolt_runner",
		description = "Unleash a rapid-fire barrage of energy bolts.",
		cooldown = 60,
		kind = "Ultimate",
		duration = 5,
		shotsPerSecond = 8,
		damagePerShot = 5,
		range = 600,
		spreadDegrees = 3,
		infiniteAmmo = true,
		color = Color3.fromRGB(255, 255, 100),
	},
}

return AbilityConfig