--!strict

-- Pulse Deck Arena v2 - Ability Configuration
-- 29 abilities across all kinds

local AbilityConfig = {

	-- === MOBILITY ===

	phase_dash = {
		id = "phase_dash",
		displayName = "Phase Dash",
		description = "Dash forward with brief invulnerability.",
		kind = "Mobility",
		cooldown = 6,
		dashDistance = 30,
		invulnerabilitySeconds = 0.4,
		leaveTrail = true,
		trailDuration = 0.6,
		trailColor = Color3.fromRGB(255, 222, 35),
		energyCost = 20,
	},

	shadow_step = {
		id = "shadow_step",
		displayName = "Shadow Step",
		description = "Teleport behind an enemy and become stealthed.",
		kind = "Mobility",
		cooldown = 10,
		dashDistance = 40,
		invulnerabilitySeconds = 0.5,
		stealthDuration = 4,
		trailColor = Color3.fromRGB(40, 40, 50),
		energyCost = 25,
	},

	time_dilation = {
		id = "time_dilation",
		displayName = "Time Dilation",
		description = "Create a zone that slows enemies and speeds you up.",
		kind = "Mobility",
		cooldown = 18,
		radius = 20,
		duration = 5,
		selfSpeedMultiplier = 1.5,
		enemySlowMultiplier = 0.4,
		energyCost = 30,
		effectColor = Color3.fromRGB(100, 150, 255),
	},

	overcharge = {
		id = "overcharge",
		displayName = "Overcharge",
		description = "Boost speed and fire rate temporarily.",
		kind = "Mobility",
		cooldown = 14,
		duration = 5,
		speedMultiplier = 1.4,
		fireRateMultiplier = 1.3,
		energyColor = Color3.fromRGB(255, 200, 50),
		energyCost = 20,
	},

	blink = {
		id = "blink",
		displayName = "Blink",
		description = "Short teleport in the direction you're moving.",
		kind = "Mobility",
		cooldown = 4,
		dashDistance = 20,
		invulnerabilitySeconds = 0.25,
		trailColor = Color3.fromRGB(200, 200, 255),
		energyCost = 10,
	},

	vault = {
		id = "vault",
		displayName = "Vault",
		description = "Leap over obstacles with an aerial boost.",
		kind = "Mobility",
		cooldown = 5,
		dashDistance = 15,
		jumpBoost = 30,
		invulnerabilitySeconds = 0.3,
		trailColor = Color3.fromRGB(80, 255, 150),
		energyCost = 15,
	},

	-- === DEFENSIVE ===

	shield_dome = {
		id = "shield_dome",
		displayName = "Shield Dome",
		description = "Deploy an energy dome that blocks damage.",
		kind = "DefensiveDeployable",
		cooldown = 16,
		radius = 14,
		duration = 8,
		domeHealth = 300,
		damageReduction = 0.7,
		healInsideAlly = 10,
		healTickInterval = 1,
		color = Color3.fromRGB(80, 180, 255),
		energyCost = 35,
	},

	fortify = {
		id = "fortify",
		displayName = "Fortify",
		description = "Enter a fortified state with massive damage reduction.",
		kind = "DefensiveSelf",
		cooldown = 20,
		duration = 5,
		damageReduction = 0.6,
		cannotMove = true,
		canFireWhileActive = true,
		effectColor = Color3.fromRGB(255, 180, 50),
		energyCost = 30,
	},

	energy_shield = {
		id = "energy_shield",
		displayName = "Energy Shield",
		description = "Project a forward energy shield that absorbs damage.",
		kind = "DefensiveDeployable",
		cooldown = 14,
		width = 6,
		height = 8,
		maxHealth = 400,
		damageAbsorption = 0.6,
		reflectChance = 0.15,
		duration = 6,
		color = Color3.fromRGB(100, 200, 255),
		energyCost = 30,
	},

	-- === OFFENSIVE ===

	tracker_mark = {
		id = "tracker_mark",
		displayName = "Tracker Mark",
		description = "Mark an enemy, increasing damage they take.",
		kind = "Debuff",
		cooldown = 8,
		range = 500,
		duration = 6,
		damageAmplify = 1.3,
		energyCost = 15,
	},

	cluster_charge = {
		id = "cluster_charge",
		displayName = "Cluster Charge",
		description = "Throw a charge that explodes into submunitions.",
		kind = "AreaBurst",
		cooldown = 10,
		fuseSeconds = 1.5,
		mainRadius = 16,
		mainDamage = 80,
		miniCount = 5,
		miniRadius = 8,
		miniDamage = 30,
		miniSpread = 10,
		objectiveMultiplier = 1.5,
		energyCost = 35,
	},

	blink_swap = {
		id = "blink_swap",
		displayName = "Blink Swap",
		description = "Blink to an enemy's position, leaving an explosive decoy.",
		kind = "Mobility",
		cooldown = 12,
		teleportDistance = 50,
		targetBlinkRange = 60,
		behindTargetOffset = 5,
		decoyExplodes = true,
		decoyDuration = 2,
		decoyRadius = 8,
		decoyDamage = 40,
		energyCost = 25,
	},

	gravity_well = {
		id = "gravity_well",
		displayName = "Gravity Well",
		description = "Create a gravity well that pulls enemies in and damages them.",
		kind = "AreaControl",
		cooldown = 15,
		radius = 18,
		pullStrength = 25,
		damagePerSecond = 40,
		duration = 6,
		color = Color3.fromRGB(180, 50, 255),
		energyCost = 40,
	},

	-- === SUPPORT ===

	heal_pulse = {
		id = "heal_pulse",
		displayName = "Heal Pulse",
		description = "Pulse healing to nearby allies and damage enemies.",
		kind = "Heal",
		cooldown = 10,
		radius = 25,
		allyHeal = 60,
		enemyDamage = 30,
		healOverTime = 10,
		healOverTimeDuration = 4,
		energyCost = 25,
	},

	rejuvenation_field = {
		id = "rejuvenation_field",
		displayName = "Rejuvenation Field",
		description = "Place a healing field that restores allies over time.",
		kind = "HealField",
		cooldown = 14,
		radius = 20,
		duration = 10,
		healPerSecond = 15,
		maxHealPerAlly = 100,
		color = Color3.fromRGB(50, 255, 150),
		energyCost = 30,
	},

	-- === UTILITY ===

	mini_sentry = {
		id = "mini_sentry",
		displayName = "Mini Sentry",
		description = "Deploy an automated turret that fires at enemies.",
		kind = "Turret",
		cooldown = 12,
		duration = 15,
		range = 200,
		damage = 12,
		fireInterval = 0.35,
		bulletSpeed = 600,
		maxTargets = 1,
		energyCost = 20,
	},

	slow_field = {
		id = "slow_field",
		displayName = "Slow Field",
		description = "Deploy a field that slows and damages enemies.",
		kind = "AreaControl",
		cooldown = 14,
		targetRange = 45,
		radius = 16,
		duration = 6,
		enemySlowMultiplier = 0.4,
		damagePerSecond = 20,
		color = Color3.fromRGB(80, 220, 255),
		energyCost = 25,
	},

	-- === NEW ABILITIES ===

	nova_burst = {
		id = "nova_burst",
		displayName = "Nova Burst",
		description = "Release a burst of energy that damages and knocks back all nearby enemies.",
		kind = "AreaBurst",
		cooldown = 12,
		radius = 22,
		damage = 90,
		knockbackForce = 50,
		energyCost = 40,
	},

	emp_blast = {
		id = "emp_blast",
		displayName = "EMP Blast",
		description = "Disable enemy abilities and shields in an area.",
		kind = "AreaBurst",
		cooldown = 16,
		radius = 20,
		duration = 4,
		energyCost = 25,
	},

	smoke_screen = {
		id = "smoke_screen",
		displayName = "Smoke Screen",
		description = "Deploy a smoke cloud that obscures vision.",
		kind = "Utility",
		cooldown = 12,
		radius = 18,
		duration = 6,
		energyCost = 15,
	},

	radar_pulse = {
		id = "radar_pulse",
		displayName = "Radar Pulse",
		description = "Reveal all enemies on the minimap for several seconds.",
		kind = "Utility",
		cooldown = 20,
		duration = 8,
		radius = 500,
		energyCost = 10,
	},

	adrenaline = {
		id = "adrenaline",
		displayName = "Adrenaline Rush",
		description = "Greatly increase speed and fire rate for a short time.",
		kind = "Mobility",
		cooldown = 18,
		duration = 4,
		speedMultiplier = 1.6,
		fireRateMultiplier = 1.4,
		energyCost = 25,
	},

	berserk = {
		id = "berserk",
		displayName = "Berserk",
		description = "Enter a frenzy with increased damage and reduced damage taken.",
		kind = "Offensive",
		cooldown = 22,
		duration = 5,
		damageMultiplier = 1.5,
		damageReduction = 0.3,
		energyCost = 30,
	},

	tactical_overlay = {
		id = "tactical_overlay",
		displayName = "Tactical Overlay",
		description = "See enemy footprints and hear their footsteps louder.",
		kind = "Utility",
		cooldown = 15,
		duration = 8,
		energyCost = 15,
	},

	tether = {
		id = "tether",
		displayName = "Energy Tether",
		description = "Link to an ally, sharing health and shielding them.",
		kind = "Support",
		cooldown = 12,
		duration = 5,
		healthShareRate = 10,
		energyCost = 20,
	},

	smart_mine = {
		id = "smart_mine",
		displayName = "Smart Mine",
		description = "Deploy a proximity mine that tracks and detonates near enemies.",
		kind = "Deployable",
		cooldown = 10,
		duration = 30,
		damage = 80,
		splashRadius = 10,
		detectionRadius = 12,
		maxMines = 3,
		energyCost = 20,
	},

	thermal_grenade = {
		id = "thermal_grenade",
		displayName = "Thermal Grenade",
		description = "Heat-seeking grenade that pursues the closest enemy.",
		kind = "Projectile",
		cooldown = 8,
		damage = 55,
		splashRadius = 12,
		splashDamage = 30,
		projectileSpeed = 100,
		seekTurnRate = 0.08,
		maxLifetime = 4,
		energyCost = 15,
	},

	black_hole = {
		id = "black_hole",
		displayName = "Black Hole",
		description = "Create a devastating singularity that pulls everything in.",
		kind = "AreaControl",
		cooldown = 25,
		radius = 22,
		pullStrength = 40,
		damagePerSecond = 60,
		duration = 4,
		energyCost = 50,
	},

	phoenix_dive = {
		id = "phoenix_dive",
		displayName = "Phoenix Dive",
		description = "Dive from the sky, exploding on impact and self-reviving.",
		kind = "Mobility",
		cooldown = 30,
		diveDamage = 120,
		blastRadius = 15,
		selfHealOnImpact = 100,
		energyCost = 45,
	},

	-- === NEW ABILITIES (continued) ===

	fire_nova = {
		id = "fire_nova",
		displayName = "Fire Nova",
		description = "Explosive burst of fire that ignites all nearby enemies.",
		kind = "AreaBurst",
		cooldown = 14,
		radius = 20,
		damage = 75,
		burnDuration = 4,
		burnDamagePerTick = 15,
		burnTickInterval = 0.5,
		knockbackForce = 35,
		energyCost = 40,
	},

	inferno = {
		id = "inferno",
		displayName = "Inferno",
		description = "Create a massive fire zone that burns everything inside.",
		kind = "AreaControl",
		cooldown = 35,
		radius = 25,
		duration = 8,
		damagePerSecond = 60,
		burnDamagePerTick = 25,
		burnTickInterval = 0.5,
		slowMultiplier = 0.5,
		energyCost = 50,
	},

	cloak_and_dagger = {
		id = "cloak_and_dagger",
		displayName = "Cloak and Dagger",
		description = "Become invisible and gain a critical damage buff for a duration.",
		kind = "Stealth",
		cooldown = 20,
		duration = 8,
		invisible = true,
		critMultiplier = 2.5,
		moveSpeedMultiplier = 1.3,
		energyCost = 30,
	},

	freeze_nova = {
		id = "freeze_nova",
		displayName = "Freeze Nova",
		description = "Burst of frost that freezes and slows all enemies in an area.",
		kind = "AreaBurst",
		cooldown = 14,
		radius = 18,
		damage = 50,
		slowMultiplier = 0.3,
		slowDuration = 3,
		freezeChance = 0.6,
		freezeDuration = 2,
		energyCost = 35,
	},

	blizzard = {
		id = "blizzard",
		displayName = "Blizzard",
		description = "Summon a devastating blizzard that freezes the entire area.",
		kind = "AreaControl",
		cooldown = 40,
		radius = 30,
		duration = 10,
		damagePerSecond = 30,
		slowMultiplier = 0.2,
		freezeChance = 0.8,
		freezeDuration = 2.5,
		energyCost = 55,
	},

	blood_frenzy = {
		id = "blood_frenzy",
		displayName = "Blood Frenzy",
		description = "Enter an uncontrollable rage with massive damage and lifesteal.",
		kind = "Offensive",
		cooldown = 30,
		duration = 8,
		damageMultiplier = 2.0,
		lifestealPercent = 0.4,
		speedMultiplier = 1.3,
		energyCost = 45,
	},

	supernova = {
		id = "supernova",
		displayName = "Supernova",
		description = "Channel a massive explosion that deals huge damage in a large area.",
		kind = "AreaBurst",
		cooldown = 35,
		radius = 30,
		damage = 150,
		knockbackForce = 80,
		duration = 6,
		chargeDamagePerSecond = 25,
		energyCost = 50,
	},
}

return AbilityConfig