local Config = {
	GAME_NAME = "PULSE DECK ARENA v2",
	MATCH_DURATION = 360,
	COUNTDOWN_DURATION = 5,
	DECK_SIZE = 5,
	MAX_SELECTABLE_HEROES = 20,
	SWITCH_COOLDOWN = 0.5,
	HERO_RESPAWN_TIME = 6,
	SUDDEN_DEATH_ENABLED = true,
	SUDDEN_DEATH_DURATION = 60,
	SOLO_BOT_START_DELAY = 4,
	SCORE_HERO_ELIMINATION = 25,
	SCORE_ASSIST = 8,
	SCORE_GENERATOR_DESTROY = 150,
	SCORE_OBJECTIVE_DAMAGE = 2,
	SCORE_KILLSTREAK_BONUS = 50,
	CORE_MAX_HEALTH = 2000,
	GENERATOR_MAX_HEALTH = 600,
	HEALTH_PICKUP_AMOUNT = 50,
	HEALTH_PICKUP_RESPAWN = 12,
	AMMO_PICKUP_AMOUNT = 30,
	AMMO_PICKUP_RESPAWN = 10,
	ENERGY_PICKUP_AMOUNT = 30,
	ENERGY_PICKUP_RESPAWN = 15,
	ARMOR_PICKUP_AMOUNT = 50,
	ARMOR_PICKUP_RESPAWN = 18,
	MAX_KILLS_FOR_MVP = 20,
	TEAM_RED = "Red",
	TEAM_BLUE = "Blue",
	TEAM_NONE = "None",
	RED_COLOR = Color3.fromRGB(255, 70, 70),
	BLUE_COLOR = Color3.fromRGB(60, 200, 255),
	NEUTRAL_COLOR = Color3.fromRGB(180, 180, 180),
	GOLD_COLOR = Color3.fromRGB(255, 215, 0),
	DAMAGE_NUMBER_COLORS = {
		normal = Color3.fromRGB(255, 255, 255),
		headshot = Color3.fromRGB(255, 50, 50),
		critical = Color3.fromRGB(255, 200, 50),
		healing = Color3.fromRGB(50, 255, 100),
		ability = Color3.fromRGB(200, 100, 255),
		armor = Color3.fromRGB(100, 200, 255),
	},
	FFA_ENABLED = true,
	BOMB_ENABLED = true,
	KOTH_ENABLED = true,
	CTF_ENABLED = true,
	FRIENDLY_FIRE_ENABLED = false,
	FFA_SCORE_LIMIT = 30,
	KOTH_HOLD_TIME = 15,
	CTF_CAPTURE_SCORE = 100,
	SCORE_FLAG_CAPTURE = 100,
	FLAG_RETURN_TIME = 30,
	MAX_PLAYERS_PER_TEAM = 5,
	BOT_COUNT = 4,
	VOICE_CHAT_ENABLED = false,

	-- === REWARD MULTIPLIERS ===
	KILLSTREAK_MULTIPLIER = 1.5,
	OBJECTIVE_MULTIPLIER = 2.0,
	WIN_MULTIPLIER = 1.5,

	-- === KILLSTREAK REWARDS ===
	KILLSTREAK_TIERS = {
		{ kills = 3, reward = "AmmoDrop", message = "%s is on fire! 3 kill streak!", duration = 3 },
		{ kills = 5, reward = "ArmorDrop", message = "%s is UNSTOPPABLE! 5 kill streak!", duration = 4 },
		{ kills = 8, reward = "HealthDrop", message = "%s is a DEMON! 8 kill streak!", duration = 5 },
		{ kills = 10, reward = "EnergyDrop", message = "GODLIKE! %s has 10 kills!", duration = 5 },
	},

	-- === XP REWARDS ===
	XP_KILL = 30,
	XP_ASSIST = 10,
	XP_OBJECTIVE_DAMAGE = 1,
	XP_OBJECTIVE_DESTROY = 100,
	XP_WIN = 150,
	XP_LOSS = 50,
	XP_DRAW = 80,
	XP_FIRST_BLOOD = 50,

	BOMB_PLANT_TIME = 3,
	BOMB_DEFUSE_TIME = 5,
	BOMB_EXPLODE_TIME = 40,
	BOMB_MAX_ROUNDS = 15,
	BOMB_ROUND_TIME = 105,
	BOMB_BUY_TIME = 20,
	BOMB_SWAP_ROUND = 8,
	BOMB_PLANT_REWARD = 300,
	BOMB_DEFUSE_REWARD = 300,
	BOMB_KILL_REWARD_CT = 200,
	BOMB_KILL_REWARD_T = 300,
	BOMB_WIN_REWARD = 3000,
	BOMB_LOSS_REWARD_BASE = 1400,
	BOMB_LOSS_REWARD_INCREMENT = 500,
	BOMB_EXPLODE_REWARD = 300,
	BOMB_DEFUSAL_HALFWAY = 0.5,
	BOMB_SITES = {
		A = Vector3.new(-80, 3, 0),
		B = Vector3.new(80, 3, 0),
	},
	BOMB_SPAWN_CT = {Vector3.new(-140, 3, 50), Vector3.new(-140, 3, -50), Vector3.new(-135, 3, 0)},
	BOMB_SPAWN_T = {Vector3.new(140, 3, 50), Vector3.new(140, 3, -50), Vector3.new(135, 3, 0)},
	BOMB_BUY_ZONE_CT = {Vector3.new(-145, 1, 0)},
	BOMB_BUY_ZONE_T = {Vector3.new(145, 1, 0)},

	-- === ECONOMY: Weapon prices (Bomb mode) ===
	WEAPON_PRICES = {
		pulse_rifle = 2000, storm_rifle = 2200, plasma_rifle = 2400, titan_rifle = 2800,
		nano_smg = 600, vortex_smg = 800, shadow_smg = 1000,
		scatter_cannon = 900, dual_blasters = 1000, pump_action = 1200,
		rail_lance = 4000, longbow = 4500, hunter_rifle = 3500,
		arc_launcher = 2000, flamethrower = 1800, cryo_rifle = 2200,
		ion_beam = 1500, rivet_carbine = 1600, phase_smg = 700,
		bio_rifle = 1200, lightning_gun = 2500, cluster_mortar = 3000,
		shotgun = 800, shadow_rifle = 1700, plasma_caster = 2000,
		vortex_rifle = 1600, gravity_hammer = 2200, energy_sword = 1800,
		twin_pistols = 400, shadow_pistols = 600,
	},
	STARTING_MONEY = 800,
	MAX_MONEY = 10000,

	-- === MAP CONFIG ===
	MAP = {
		RED_CORE = Vector3.new(-150, 8, 0),
		BLUE_CORE = Vector3.new(150, 8, 0),
		RED_GENERATORS = {
			Vector3.new(-120, 6, 40),
			Vector3.new(-120, 6, -40),
			Vector3.new(-95, 6, 0),
			Vector3.new(-145, 6, 20),
			Vector3.new(-145, 6, -20),
		},
		BLUE_GENERATORS = {
			Vector3.new(120, 6, 40),
			Vector3.new(120, 6, -40),
			Vector3.new(95, 6, 0),
			Vector3.new(145, 6, 20),
			Vector3.new(145, 6, -20),
		},
		RED_SPAWN_PADS = {
			Vector3.new(-155, 3, 25),
			Vector3.new(-155, 3, -25),
			Vector3.new(-140, 3, 0),
			Vector3.new(-150, 3, 12),
			Vector3.new(-150, 3, -12),
		},
		BLUE_SPAWN_PADS = {
			Vector3.new(155, 3, 25),
			Vector3.new(155, 3, -25),
			Vector3.new(140, 3, 0),
			Vector3.new(150, 3, 12),
			Vector3.new(150, 3, -12),
		},
		POWERUP_SPAWNS = {
			Vector3.new(0, 3, 0),
			Vector3.new(-70, 3, 50),
			Vector3.new(70, 3, -50),
			Vector3.new(-50, 3, -60),
			Vector3.new(50, 3, 60),
			Vector3.new(0, 3, 60),
			Vector3.new(0, 3, -60),
		},
		FFA_SPAWNS = {
			Vector3.new(0, 5, 0),
			Vector3.new(-60, 5, 60),
			Vector3.new(60, 5, -60),
			Vector3.new(-80, 5, -20),
			Vector3.new(80, 5, 20),
			Vector3.new(0, 5, -80),
			Vector3.new(0, 5, 80),
			Vector3.new(-40, 5, 0),
			Vector3.new(40, 5, 0),
		},
		KOTH_ZONE = Vector3.new(0, 2, 0),
		CtfFlagRed = Vector3.new(-135, 3, 0),
		CtfFlagBlue = Vector3.new(135, 3, 0),
	},

	PRESETS = {
		assault = {"bolt_runner", "nova", "glitch_byte", "fuse_jack", "reaper", "pyro_blazer", "vector"},
		defense = {"iron_bulwark", "terra_pin", "wisp_ion", "vesper_scope", "bastion", "berserker", "medic"},
		balanced = {"bolt_runner", "iron_bulwark", "vesper_scope", "patch_flux", "fuse_jack", "medic", "chrono"},
		storm_sniper = {
			"storm_sniper", "nova", "glitch_byte", "bolt_runner", "vesper_scope"
		},
		chaos = {"glitch_byte", "reaper", "fuse_jack", "wisp_ion", "nova", "phoenix", "berserker"},
	},

	DEFAULT_DECK = {"bolt_runner", "iron_bulwark", "vesper_scope", "patch_flux", "fuse_jack"},

	BOT_DECK = {"glitch_byte", "terra_pin", "wisp_ion", "iron_bulwark", "fuse_jack", "reaper", "nova", "bastion", "storm_sniper", "phoenix"},

	ADMIN_USER_IDS = {},
	MAX_HEALTH_KITS = 5,
	MAX_AMMO_CRATES = 5,
	MAX_ARMOR_STATIONS = 3,

	-- === BATTLE PASS ===
	BP_XP_PER_TIER_BASE = 500,
	BP_XP_INCREMENT = 150,
	BP_MAX_TIER = 50,
	BP_PREMIUM_COST = 1500,

	-- === SHOP ===
	SHOP_ITEMS = {
		-- Skin bundles
		{id = "skin_bundle_assault", name = "Assault Skin Bundle", price = 500, items = {"bolt_runner_gold", "nova_stellar"}, category = "Skins"},
		{id = "skin_bundle_tank", name = "Tank Skin Bundle", price = 500, items = {"iron_bulwark_titanium", "bastion_ironclad"}, category = "Skins"},
		{id = "skin_bundle_mage", name = "Mage Skin Bundle", price = 500, items = {"phoenix_solar", "cryomancer_frostbitten"}, category = "Skins"},
		-- Individual skins
		{id = "skin_legendary", name = "Random Legendary Skin", price = 1500, items = {}, category = "Skins"},
		-- Hero unlocks
		{id = "hero_unlock", name = "Unlock Random Hero", price = 400, items = {}, category = "Heroes"},
		-- Currency
		{id = "coins_500", name = "500 Coins", price = 99, items = {}, category = "Currency"},
		{id = "coins_1500", name = "1500 Coins", price = 249, items = {}, category = "Currency"},
		{id = "coins_4000", name = "4000 Coins", price = 599, items = {}, category = "Currency"},
	},
	SHOP_CATEGORIES = {"Skins", "Heroes", "Currency"},
}

return Config