--!strict
local Config = {
	GAME_NAME = "PULSE DECK ARENA v2",
	MATCH_DURATION = 360,
	COUNTDOWN_DURATION = 5,
	DECK_SIZE = 5,
	MAX_SELECTABLE_HEROES = 20,
	SWITCH_COOLDOWN = 0.5,
	HERO_RESPAWN_TIME = 6,
	SUDDEN_DEATH_ENABLED = true,
	SUDDEN_DEATH_DURATION = 60,
	SOLO_BOT_START_DELAY = 4,
	SCORE_HERO_ELIMINATION = 25,
	SCORE_ASSIST = 8,
	SCORE_GENERATOR_DESTROY = 150,
	SCORE_OBJECTIVE_DAMAGE = 2,
	SCORE_KILLSTREAK_BONUS = 50,
	CORE_MAX_HEALTH = 2000,
	GENERATOR_MAX_HEALTH = 600,
	HEALTH_PICKUP_AMOUNT = 50,
	HEALTH_PICKUP_RESPAWN = 12,
	AMMO_PICKUP_AMOUNT = 30,
	AMMO_PICKUP_RESPAWN = 10,
	ENERGY_PICKUP_AMOUNT = 30,
	ENERGY_PICKUP_RESPAWN = 15,
	ARMOR_PICKUP_AMOUNT = 50,
	ARMOR_PICKUP_RESPAWN = 18,
	MAX_KILLS_FOR_MVP = 20,
	TEAM_RED = "Red",
	TEAM_BLUE = "Blue",
	TEAM_NONE = "None",
	RED_COLOR = Color3.fromRGB(255, 70, 70),
	BLUE_COLOR = Color3.fromRGB(60, 200, 255),
	NEUTRAL_COLOR = Color3.fromRGB(180, 180, 180),
	GOLD_COLOR = Color3.fromRGB(255, 215, 0),
	DAMAGE_NUMBER_COLORS = {
		normal = Color3.fromRGB(255, 255, 255),
		headshot = Color3.fromRGB(255, 50, 50),
		critical = Color3.fromRGB(255, 200, 50),
		healing = Color3.fromRGB(50, 255, 100),
		ability = Color3.fromRGB(200, 100, 255),
		armor = Color3.fromRGB(100, 200, 255),
	},
	FFA_ENABLED = true,
	KOTH_ENABLED = true,
	CTF_ENABLED = true,
	FRIENDLY_FIRE_ENABLED = false,
	FFA_SCORE_LIMIT = 30,
	KOTH_HOLD_TIME = 15,
	CTF_CAPTURE_SCORE = 100,
	FLAG_RETURN_TIME = 30,
	MAX_PLAYERS_PER_TEAM = 5,
	BOT_COUNT = 4,
	VOICE_CHAT_ENABLED = false,

	-- === REWARD MULTIPLIERS ===
	KILLSTREAK_MULTIPLIER = 1.5,
	OBJECTIVE_MULTIPLIER = 2.0,
	WIN_MULTIPLIER = 1.5,

	-- === KILLSTREAK REWARDS ===
	KILLSTREAK_TIERS = {
		{ kills = 3, reward = "AmmoDrop", message = "%s is on fire! 3 kill streak!", duration = 3 },
		{ kills = 5, reward = "ArmorDrop", message = "%s is UNSTOPPABLE! 5 kill streak!", duration = 4 },
		{ kills = 8, reward = "HealthDrop", message = "%s is a DEMON! 8 kill streak!", duration = 5 },
		{ kills = 10, reward = "EnergyDrop", message = "GODLIKE! %s has 10 kills!", duration = 5 },
	},

	-- === XP REWARDS ===
	XP_KILL = 30,
	XP_ASSIST = 10,
	XP_OBJECTIVE_DAMAGE = 1,
	XP_OBJECTIVE_DESTROY = 100,
	XP_WIN = 150,
	XP_LOSS = 50,
	XP_DRAW = 80,
	XP_FIRST_BLOOD = 50,

	-- === MAP CONFIG ===
	MAP = {
		RED_CORE = Vector3.new(-150, 8, 0),
		BLUE_CORE = Vector3.new(150, 8, 0),
		RED_GENERATORS = {
			Vector3.new(-120, 6, 40),
			Vector3.new(-120, 6, -40),
			Vector3.new(-95, 6, 0),
			Vector3.new(-145, 6, 20),
			Vector3.new(-145, 6, -20),
		},
		BLUE_GENERATORS = {
			Vector3.new(120, 6, 40),
			Vector3.new(120, 6, -40),
			Vector3.new(95, 6, 0),
			Vector3.new(145, 6, 20),
			Vector3.new(145, 6, -20),
		},
		RED_SPAWN_PADS = {
			Vector3.new(-155, 3, 25),
			Vector3.new(-155, 3, -25),
			Vector3.new(-140, 3, 0),
			Vector3.new(-150, 3, 12),
			Vector3.new(-150, 3, -12),
		},
		BLUE_SPAWN_PADS = {
			Vector3.new(155, 3, 25),
			Vector3.new(155, 3, -25),
			Vector3.new(140, 3, 0),
			Vector3.new(150, 3, 12),
			Vector3.new(150, 3, -12),
		},
		POWERUP_SPAWNS = {
			Vector3.new(0, 3, 0),
			Vector3.new(-70, 3, 50),
			Vector3.new(70, 3, -50),
			Vector3.new(-50, 3, -60),
			Vector3.new(50, 3, 60),
			Vector3.new(0, 3, 60),
			Vector3.new(0, 3, -60),
		},
		FFA_SPAWNS = {
			Vector3.new(0, 5, 0),
			Vector3.new(-60, 5, 60),
			Vector3.new(60, 5, -60),
			Vector3.new(-80, 5, -20),
			Vector3.new(80, 5, 20),
			Vector3.new(0, 5, -80),
			Vector3.new(0, 5, 80),
			Vector3.new(-40, 5, 0),
			Vector3.new(40, 5, 0),
		},
		KOTH_ZONE = Vector3.new(0, 2, 0),
		CtfFlagRed = Vector3.new(-135, 3, 0),
		CtfFlagBlue = Vector3.new(135, 3, 0),
	},

	PRESETS = {
		assault = {"bolt_runner", "nova", "glitch_byte", "fuse_jack", "reaper", "pyro_blazer", "vector"},
		defense = {"iron_bulwark", "terra_pin", "wisp_ion", "vesper_scope", "bastion", "sentinel", "berserker"},
		balanced = {"bolt_runner", "iron_bulwark", "vesper_scope", "patch_flux", "fuse_jack", "medic", "chrono"},
		sniper = {"vesper_scope", "storm_sniper", "nova", "glitch_byte", "bolt_runner"},
		chaos = {"glitch_byte", "reaper", "fuse_jack", "wisp_ion", "nova", "phoenix", "havoc"},
	},

	DEFAULT_DECK = {"bolt_runner", "iron_bulwark", "vesper_scope", "patch_flux", "fuse_jack"},

	BOT_DECK = {"glitch_byte", "terra_pin", "wisp_ion", "iron_bulwark", "fuse_jack", "reaper", "nova", "bastion", "storm_sniper", "phoenix"},

	ADMIN_USER_IDS = {},
	MAX_HEALTH_KITS = 5,
	MAX_AMMO_CRATES = 5,
	MAX_ARMOR_STATIONS = 3,
}

return Config