--!strict

-- Pulse Deck Arena - Hero Configuration
-- Each hero has unique stats, weapons, abilities, cosmetics, and powers

local HeroConfig = {

	-- === ASSAULT HEROES ===

	bolt_runner = {
		id = "bolt_runner",
		displayName = "Bolt Runner",
		role = "Assault",
		maxHealth = 150,
		walkSpeed = 22,
		jumpPower = 55,
		weaponId = "pulse_rifle",
		abilityId = "phase_dash",
		ultimateId = "thermal_grenade",
		difficulty = 1,
		aiProfile = "Flanker",
		primaryColor = Color3.fromRGB(255, 222, 35),
		secondaryColor = Color3.fromRGB(35, 35, 40),
		accentColor = Color3.fromRGB(255, 180, 0),
		shortDescription = "Mobile rifle duelist with a quick dash.",
		lore = "Fastest scout in the arena, striking with precision and speed.",
		-- Cosmetics / Skin
		skins = {
			default = {
				bodyColor = Color3.fromRGB(255, 222, 35),
				shirtColor = Color3.fromRGB(40, 40, 50),
				pantsColor = Color3.fromRGB(30, 30, 38),
				helmet = true,
				visorColor = Color3.fromRGB(200, 255, 255),
				shoulderArmor = false,
			},
			gold = {
				bodyColor = Color3.fromRGB(255, 215, 0),
				shirtColor = Color3.fromRGB(60, 50, 20),
				pantsColor = Color3.fromRGB(40, 35, 15),
				helmet = true,
				visorColor = Color3.fromRGB(255, 255, 200),
				shoulderArmor = true,
				rarity = "Legendary",
			},
			shadow = {
				bodyColor = Color3.fromRGB(60, 60, 70),
				shirtColor = Color3.fromRGB(20, 20, 25),
				pantsColor = Color3.fromRGB(15, 15, 20),
				helmet = true,
				visorColor = Color3.fromRGB(255, 50, 50),
				shoulderArmor = false,
				rarity = "Epic",
			},
		},
		-- Clothing
		clothes = {
			default = {
				shirt = "Classic Tee",
				pants = "Tactical Pants",
				cape = false,
			},
			armored = {
				shirt = "Heavy Vest",
				pants = "Reinforced Trousers",
				cape = false,
				rarity = "Rare",
			},
		},
		-- Powers
		powers = {
			speedBoost = {name = "Speed Boost", description = "Temporarily increases movement speed", multiplier = 1.3, duration = 3},
		},
		weaponSkin = "Default",
		killEffect = "ElectricShock",
	},

	iron_bulwark = {
		id = "iron_bulwark",
		displayName = "Iron Bulwark",
		role = "Tank",
		maxHealth = 300,
		walkSpeed = 14,
		jumpPower = 42,
		weaponId = "scatter_cannon",
		abilityId = "shield_dome",
		ultimateId = "fortify",
		difficulty = 2,
		aiProfile = "Frontline",
		primaryColor = Color3.fromRGB(128, 136, 145),
		secondaryColor = Color3.fromRGB(255, 128, 35),
		accentColor = Color3.fromRGB(80, 90, 100),
		shortDescription = "Heavy frontliner with shotgun pressure and dome shield.",
		lore = "An immovable fortress, crushing all who dare stand against him.",
		skins = {
			default = {
				bodyColor = Color3.fromRGB(128, 136, 145),
				shirtColor = Color3.fromRGB(60, 65, 70),
				pantsColor = Color3.fromRGB(50, 55, 60),
				helmet = true,
				visorColor = Color3.fromRGB(200, 200, 210),
				shoulderArmor = true,
			},
			titanium = {
				bodyColor = Color3.fromRGB(180, 190, 200),
				shirtColor = Color3.fromRGB(40, 45, 55),
				pantsColor = Color3.fromRGB(35, 40, 50),
				helmet = true,
				visorColor = Color3.fromRGB(150, 200, 255),
				shoulderArmor = true,
				rarity = "Legendary",
				metalness = 1.0,
			},
			rustLord = {
				bodyColor = Color3.fromRGB(160, 120, 60),
				shirtColor = Color3.fromRGB(80, 50, 20),
				pantsColor = Color3.fromRGB(60, 35, 10),
				helmet = true,
				visorColor = Color3.fromRGB(255, 180, 50),
				shoulderArmor = true,
				rarity = "Epic",
			},
		},
		clothes = {
			default = {
				shirt = "Plate Carrier",
				pants = "Heavy Armor Pants",
				cape = false,
			},
			royal = {
				shirt = "Royal Guard Vest",
				pants = "Royal Greaves",
				cape = true,
				capeColor = Color3.fromRGB(200, 50, 50),
				rarity = "Legendary",
			},
		},
		powers = {
			damageResistance = {name = "Damage Resistance", description = "Reduces all incoming damage", reduction = 0.15, duration = 5},
		},
		weaponSkin = "Chrome",
		killEffect = "GroundSlam",
	},

	-- === SNIPER HEROES ===

	vesper_scope = {
		id = "vesper_scope",
		displayName = "Vesper Scope",
		role = "Sniper",
		maxHealth = 110,
		walkSpeed = 16,
		jumpPower = 45,
		weaponId = "rail_lance",
		abilityId = "tracker_mark",
		ultimateId = "time_dilation",
		difficulty = 3,
		aiProfile = "Backline",
		primaryColor = Color3.fromRGB(150, 75, 255),
		secondaryColor = Color3.fromRGB(15, 15, 20),
		accentColor = Color3.fromRGB(200, 150, 255),
		shortDescription = "Long-range precision hero that marks enemies.",
		lore = "No one escapes the gaze of Vesper. Every shot finds its mark.",
		skins = {
			default = {
				bodyColor = Color3.fromRGB(150, 75, 255),
				shirtColor = Color3.fromRGB(30, 20, 50),
				pantsColor = Color3.fromRGB(25, 15, 45),
				helmet = true,
				visorColor = Color3.fromRGB(180, 120, 255),
				shoulderArmor = false,
			},
			cosmic = {
				bodyColor = Color3.fromRGB(80, 40, 140),
				shirtColor = Color3.fromRGB(10, 5, 20),
				pantsColor = Color3.fromRGB(8, 3, 15),
				helmet = true,
				visorColor = Color3.fromRGB(255, 200, 255),
				shoulderArmor = true,
				rarity = "Legendary",
				emissive = true,
				glowColor = Color3.fromRGB(100, 50, 200),
			},
		},
		clothes = {
			default = {
				shirt = "Sniper Cloak",
				pants = "Stealth Trousers",
				cape = true,
				capeColor = Color3.fromRGB(80, 40, 120),
			},
		},
		powers = {
			wallHack = {name = "Wall Hack", description = "Enemies become visible through walls", duration = 4},
		},
		weaponSkin = "Camo",
		killEffect = "Disintegration",
	},

	-- === SUPPORT HEROES ===

	patch_flux = {
		id = "patch_flux",
		displayName = "Patch Flux",
		role = "Support",
		maxHealth = 140,
		walkSpeed = 19,
		jumpPower = 48,
		weaponId = "nano_smg",
		abilityId = "heal_pulse",
		ultimateId = "rejuvenation_field",
		difficulty = 2,
		aiProfile = "Support",
		primaryColor = Color3.fromRGB(92, 255, 180),
		secondaryColor = Color3.fromRGB(245, 245, 245),
		accentColor = Color3.fromRGB(50, 255, 150),
		shortDescription = "Fast support who heals allies and chips enemies.",
		lore = "The heart of any team, keeping everyone alive with nanotech mastery.",
		skins = {
			default = {
				bodyColor = Color3.fromRGB(92, 255, 180),
				shirtColor = Color3.fromRGB(20, 50, 45),
				pantsColor = Color3.fromRGB(15, 40, 35),
				helmet = false,
				visorColor = Color3.fromRGB(150, 255, 220),
				shoulderArmor = false,
			},
			angel = {
				bodyColor = Color3.fromRGB(200, 255, 230),
				shirtColor = Color3.fromRGB(30, 40, 60),
				pantsColor = Color3.fromRGB(25, 35, 55),
				helmet = true,
				visorColor = Color3.fromRGB(255, 255, 200),
				shoulderArmor = true,
				hasWings = true,
				rarity = "Legendary",
			},
		},
		clothes = {
			default = {
				shirt = "Medic Jacket",
				pants = "Combat Medic Pants",
				cape = false,
			},
			holy = {
				shirt = "Priest Robe",
				pants = "White Trousers",
				cape = true,
				capeColor = Color3.fromRGB(255, 255, 200),
				rarity = "Epic",
			},
		},
		powers = {
			teamHeal = {name = "Team Heal", description = "Instantly heal all nearby allies", amount = 30, radius = 20},
		},
		weaponSkin = "Neon",
		killEffect = "HealBurst",
	},

	fuse_jack = {
		id = "fuse_jack",
		displayName = "Fuse Jack",
		role = "Demolition",
		maxHealth = 165,
		walkSpeed = 17,
		jumpPower = 48,
		weaponId = "arc_launcher",
		abilityId = "cluster_charge",
		ultimateId = "thermal_grenade",
		difficulty = 2,
		aiProfile = "Siege",
		primaryColor = Color3.fromRGB(255, 82, 36),
		secondaryColor = Color3.fromRGB(95, 58, 35),
		accentColor = Color3.fromRGB(255, 140, 50),
		shortDescription = "Explosive objective breaker with splash damage.",
		lore = "Where Fuse Jack goes, explosions follow. Boom is his language.",
		skins = {
			default = {
				bodyColor = Color3.fromRGB(255, 82, 36),
				shirtColor = Color3.fromRGB(60, 30, 15),
				pantsColor = Color3.fromRGB(50, 25, 10),
				helmet = false,
				visorColor = Color3.fromRGB(255, 200, 100),
				shoulderArmor = false,
			},
			pyro = {
				bodyColor = Color3.fromRGB(200, 50, 20),
				shirtColor = Color3.fromRGB(40, 15, 5),
				pantsColor = Color3.fromRGB(30, 10, 5),
				helmet = true,
				visorColor = Color3.fromRGB(255, 100, 30),
				shoulderArmor = true,
				rarity = "Epic",
			},
		},
		clothes = {
			default = {
				shirt = "Demolition Vest",
				pants = "Cargo Combat Pants",
				cape = false,
			},
			heavy = {
				shirt = "Explosive Expert Jacket",
				pants = "Reinforced Demolition Pants",
				cape = false,
				rarity = "Rare",
			},
		},
		powers = {
			blastWave = {name = "Blast Wave", description = "Creates a shockwave that knocks back all nearby enemies", radius = 15, force = 70},
		},
		weaponSkin = "Fire",
		killEffect = "BigExplosion",
	},

	-- === SKIRMISHER HEROES ===

	glitch_byte = {
		id = "glitch_byte",
		displayName = "Glitch Byte",
		role = "Skirmisher",
		maxHealth = 130,
		walkSpeed = 23,
		jumpPower = 58,
		weaponId = "phase_smg",
		abilityId = "blink_swap",
		ultimateId = "nova_burst",
		difficulty = 3,
		aiProfile = "Assassin",
		primaryColor = Color3.fromRGB(255, 45, 210),
		secondaryColor = Color3.fromRGB(10, 10, 16),
		accentColor = Color3.fromRGB(255, 100, 255),
		shortDescription = "High mobility ambusher with short teleport.",
		lore = "A digital phantom, appearing and disappearing in the blink of an eye.",
		skins = {
			default = {
				bodyColor = Color3.fromRGB(255, 45, 210),
				shirtColor = Color3.fromRGB(20, 5, 35),
				pantsColor = Color3.fromRGB(15, 3, 25),
				helmet = false,
				visorColor = Color3.fromRGB(255, 150, 255),
				shoulderArmor = false,
			},
			digital = {
				bodyColor = Color3.fromRGB(180, 30, 160),
				shirtColor = Color3.fromRGB(10, 10, 15),
				pantsColor = Color3.fromRGB(5, 5, 10),
				helmet = true,
				visorColor = Color3.fromRGB(0, 255, 200),
				shoulderArmor = false,
				rarity = "Epic",
				emissive = true,
				glowColor = Color3.fromRGB(100, 0, 255),
			},
		},
		clothes = {
			default = {
				shirt = "Hacker Jacket",
				pants = "Cyber Pants",
				cape = false,
			},
			stealth = {
				shirt = "Shadow Cloak",
				pants = "Dark Trousers",
				cape = true,
				capeColor = Color3.fromRGB(40, 0, 60),
				rarity = "Rare",
			},
		},
		powers = {
			phaseCloak = {name = "Phase Cloak", description = "Become invisible for a short duration", duration = 2.5},
		},
		weaponSkin = "Neon",
		killEffect = "GlitchExplode",
	},

	-- === ENGINEER HEROES ===

	terra_pin = {
		id = "terra_pin",
		displayName = "Terra Pin",
		role = "Engineer",
		maxHealth = 160,
		walkSpeed = 18,
		jumpPower = 45,
		weaponId = "rivet_carbine",
		abilityId = "mini_sentry",
		ultimateId = "smart_mine",
		difficulty = 2,
		aiProfile = "Defender",
		primaryColor = Color3.fromRGB(204, 174, 120),
		secondaryColor = Color3.fromRGB(35, 180, 170),
		accentColor = Color3.fromRGB(220, 200, 100),
		shortDescription = "Defensive engineer who deploys a temporary sentry turret.",
		lore = "Master engineer Terra Pin builds deadly automated defenses.",
		skins = {
			default = {
				bodyColor = Color3.fromRGB(204, 174, 120),
				shirtColor = Color3.fromRGB(50, 60, 70),
				pantsColor = Color3.fromRGB(40, 50, 60),
				helmet = true,
				visorColor = Color3.fromRGB(150, 220, 200),
				shoulderArmor = false,
			},
			mechTech = {
				bodyColor = Color3.fromRGB(180, 160, 100),
				shirtColor = Color3.fromRGB(30, 40, 50),
				pantsColor = Color3.fromRGB(25, 35, 45),
				helmet = true,
				visorColor = Color3.fromRGB(100, 255, 200),
				shoulderArmor = true,
				rarity = "Rare",
			},
		},
		clothes = {
			default = {
				shirt = "Engineer Jacket",
				pants = "Work Pants",
				cape = false,
			},
			tactical = {
				shirt = "Tactical Harness",
				pants = "Camo Pants",
				cape = false,
				rarity = "Rare",
			},
		},
		powers = {
			barrier = {name = "Barrier", description = "Place a temporary health barrier on any surface", health = 100, duration = 8},
		},
		weaponSkin = "Woodland",
		killEffect = "TurretKill",
	},

	-- === CONTROLLER HEROES ===

	wisp_ion = {
		id = "wisp_ion",
		displayName = "Wisp Ion",
		role = "Controller",
		maxHealth = 135,
		walkSpeed = 19,
		jumpPower = 52,
		weaponId = "ion_beam",
		abilityId = "slow_field",
		ultimateId = "energy_shield",
		difficulty = 2,
		aiProfile = "Controller",
		primaryColor = Color3.fromRGB(55, 230, 255),
		secondaryColor = Color3.fromRGB(170, 80, 255),
		accentColor = Color3.fromRGB(100, 255, 255),
		shortDescription = "Beam controller who slows grouped enemies.",
		lore = "Commander of the ethereal, bending energy to his will.",
		skins = {
			default = {
				bodyColor = Color3.fromRGB(55, 230, 255),
				shirtColor = Color3.fromRGB(20, 40, 80),
				pantsColor = Color3.fromRGB(15, 30, 60),
				helmet = true,
				visorColor = Color3.fromRGB(150, 255, 255),
				shoulderArmor = false,
			},
			nebula = {
				bodyColor = Color3.fromRGB(100, 50, 200),
				shirtColor = Color3.fromRGB(15, 10, 30),
				pantsColor = Color3.fromRGB(10, 5, 20),
				helmet = true,
				visorColor = Color3.fromRGB(200, 150, 255),
				shoulderArmor = true,
				rarity = "Legendary",
				emissive = true,
				glowColor = Color3.fromRGB(80, 0, 255),
			},
		},
		clothes = {
			default = {
				shirt = "Energy Harness",
				pants = "Plasma Trousers",
				cape = true,
				capeColor = Color3.fromRGB(40, 100, 200),
			},
		},
		powers = {
			energyDrain = {name = "Energy Drain", description = "Drains health from nearby enemies over time", dps = 10, radius = 12, duration = 4},
		},
		weaponSkin = "Energy",
		killEffect = "EnergyBurst",
	},

	-- === NEW HEROES ===

	reaper = {
		id = "reaper",
		displayName = "Reaper",
		role = "Flanker",
		maxHealth = 175,
		walkSpeed = 21,
		jumpPower = 50,
		weaponId = "shotgun",
		abilityId = "shadow_step",
		ultimateId = "gravity_well",
		difficulty = 2,
		aiProfile = "Flanker",
		primaryColor = Color3.fromRGB(45, 45, 55),
		secondaryColor = Color3.fromRGB(180, 50, 50),
		accentColor = Color3.fromRGB(80, 80, 100),
		shortDescription = "Close-range terror with shadow teleport.",
		lore = "Death walks silently through the shadows.",
		skins = {
			default = {
				bodyColor = Color3.fromRGB(45, 45, 55),
				shirtColor = Color3.fromRGB(25, 25, 30),
				pantsColor = Color3.fromRGB(20, 20, 25),
				helmet = true,
				visorColor = Color3.fromRGB(255, 80, 80),
				shoulderArmor = false,
			},
			death = {
				bodyColor = Color3.fromRGB(30, 30, 35),
				shirtColor = Color3.fromRGB(10, 10, 15),
				pantsColor = Color3.fromRGB(5, 5, 10),
				helmet = true,
				visorColor = Color3.fromRGB(255, 30, 30),
				shoulderArmor = true,
				rarity = "Legendary",
			},
		},
		clothes = {
			default = {
				shirt = "Reaper Hoodie",
				pants = "Dark Combat Pants",
				cape = true,
				capeColor = Color3.fromRGB(30, 30, 40),
			},
		},
		powers = {
			lifeDrain = {name = "Life Drain", description = "Melee kills restore health", amount = 25},
		},
		weaponSkin = "Dark",
		killEffect = "ShadowKill",
	},

	chrono = {
		id = "chrono",
		displayName = "Chrono",
		role = "Controller",
		maxHealth = 125,
		walkSpeed = 17,
		jumpPower = 48,
		weaponId = "vortex_rifle",
		abilityId = "time_dilation",
		ultimateId = "overcharge",
		difficulty = 3,
		aiProfile = "Controller",
		primaryColor = Color3.fromRGB(80, 130, 255),
		secondaryColor = Color3.fromRGB(20, 30, 60),
		accentColor = Color3.fromRGB(150, 200, 255),
		shortDescription = "Time-bending strategist with devastating charged shots.",
		lore = "Master of temporal manipulation, Chrono controls the flow of battle.",
		skins = {
			default = {
				bodyColor = Color3.fromRGB(80, 130, 255),
				shirtColor = Color3.fromRGB(15, 25, 50),
				pantsColor = Color3.fromRGB(10, 20, 40),
				helmet = true,
				visorColor = Color3.fromRGB(180, 220, 255),
				shoulderArmor = false,
			},
			temporal = {
				bodyColor = Color3.fromRGB(50, 80, 180),
				shirtColor = Color3.fromRGB(5, 10, 30),
				pantsColor = Color3.fromRGB(3, 8, 20),
				helmet = true,
				visorColor = Color3.fromRGB(200, 230, 255),
				shoulderArmor = true,
				rarity = "Legendary",
				emissive = true,
				glowColor = Color3.fromRGB(50, 100, 255),
			},
		},
		clothes = {
			default = {
				shirt = "Time Keeper Robe",
				pants = "Temporal Pants",
				cape = true,
				capeColor = Color3.fromRGB(40, 60, 150),
			},
		},
		powers = {
			timeFreeze = {name = "Time Freeze", description = "Briefly freezes all enemies in an area", radius = 12, duration = 2},
		},
		weaponSkin = "Chrome",
		killEffect = "TimeSnap",
	},

	nova = {
		id = "nova",
		displayName = "Nova",
		role = "Mage",
		maxHealth = 120,
		walkSpeed = 18,
		jumpPower = 50,
		weaponId = "plasma_caster",
		abilityId = "nova_burst",
		ultimateId = "overcharge",
		difficulty = 3,
		aiProfile = "Backline",
		primaryColor = Color3.fromRGB(255, 80, 180),
		secondaryColor = Color3.fromRGB(40, 15, 60),
		accentColor = Color3.fromRGB(255, 150, 220),
		shortDescription = "Devastating plasma mage with area control.",
		lore = "Raw plasma energy courses through Nova's veins.",
		skins = {
			default = {
				bodyColor = Color3.fromRGB(255, 80, 180),
				shirtColor = Color3.fromRGB(50, 10, 40),
				pantsColor = Color3.fromRGB(40, 5, 30),
				helmet = false,
				visorColor = Color3.fromRGB(255, 200, 255),
				shoulderArmor = false,
			},
			stellar = {
				bodyColor = Color3.fromRGB(200, 50, 150),
				shirtColor = Color3.fromRGB(30, 5, 25),
				pantsColor = Color3.fromRGB(20, 3, 15),
				helmet = true,
				visorColor = Color3.fromRGB(255, 150, 255),
				shoulderArmor = true,
				rarity = "Legendary",
				emissive = true,
				glowColor = Color3.fromRGB(255, 50, 200),
			},
		},
		clothes = {
			default = {
				shirt = "Mage Robe",
				pants = "Mystic Trousers",
				cape = true,
				capeColor = Color3.fromRGB(180, 30, 100),
			},
		},
		powers = {
			plasmaShield = {name = "Plasma Shield", description = "Absorb incoming damage as energy", maxShield = 100, duration = 5},
		},
		weaponSkin = "Energy",
		killEffect = "PlasmaExplode",
	},

	bastion = {
		id = "bastion",
		displayName = "Bastion",
		role = "Defender",
		maxHealth = 320,
		walkSpeed = 13,
		jumpPower = 40,
		weaponId = "gravity_hammer",
		abilityId = "energy_shield",
		ultimateId = "fortify",
		difficulty = 2,
		aiProfile = "Frontline",
		primaryColor = Color3.fromRGB(200, 100, 50),
		secondaryColor = Color3.fromRGB(60, 30, 15),
		accentColor = Color3.fromRGB(255, 150, 80),
		shortDescription = "Immovable fortress with devastating hammer.",
		lore = "The last line of defense. Nothing gets past Bastion.",
		skins = {
			default = {
				bodyColor = Color3.fromRGB(200, 100, 50),
				shirtColor = Color3.fromRGB(50, 25, 10),
				pantsColor = Color3.fromRGB(40, 20, 8),
				helmet = true,
				visorColor = Color3.fromRGB(255, 200, 150),
				shoulderArmor = true,
			},
			ironclad = {
				bodyColor = Color3.fromRGB(160, 80, 30),
				shirtColor = Color3.fromRGB(30, 15, 5),
				pantsColor = Color3.fromRGB(20, 10, 3),
				helmet = true,
				visorColor = Color3.fromRGB(255, 180, 100),
				shoulderArmor = true,
				rarity = "Epic",
			},
		},
		clothes = {
			default = {
				shirt = "Warrior Chestplate",
				pants = "Battle Greaves",
				cape = false,
			},
			ancient = {
				shirt = "Ancient Armor",
				pants = "Ancient Greaves",
				cape = true,
				capeColor = Color3.fromRGB(180, 80, 30),
				rarity = "Legendary",
			},
		},
		powers = {
			groundSlam = {name = "Ground Slam", description = "Stuns all enemies in radius", radius = 14, stunDuration = 2},
		},
		weaponSkin = "Fire",
		killEffect = "HammerSlam",
	},

	-- === SNIPER HEROES (continued) ===

	storm_sniper = {
		id = "storm_sniper",
		displayName = "Storm Sniper",
		role = "Sniper",
		maxHealth = 115,
		walkSpeed = 18,
		jumpPower = 48,
		weaponId = "storm_sniper",
		abilityId = "phase_dash",
		ultimateId = "overcharge",
		difficulty = 2,
		aiProfile = "Backline",
		primaryColor = Color3.fromRGB(130, 180, 255),
		secondaryColor = Color3.fromRGB(20, 30, 60),
		accentColor = Color3.fromRGB(100, 200, 255),
		shortDescription = "Fast semi-auto sniper with tactical mobility.",
		lore = "Storm Sniper strikes from afar and vanishes before retaliation.",
		skins = {
			default = {
				bodyColor = Color3.fromRGB(130, 180, 255),
				shirtColor = Color3.fromRGB(20, 30, 60),
				pantsColor = Color3.fromRGB(15, 20, 50),
				helmet = true,
				visorColor = Color3.fromRGB(180, 220, 255),
				shoulderArmor = false,
			},
			tempest = {
				bodyColor = Color3.fromRGB(60, 100, 200),
				shirtColor = Color3.fromRGB(10, 15, 40),
				pantsColor = Color3.fromRGB(8, 12, 30),
				helmet = true,
				visorColor = Color3.fromRGB(200, 240, 255),
				shoulderArmor = true,
				rarity = "Legendary",
				emissive = true,
				glowColor = Color3.fromRGB(100, 150, 255),
			},
		},
		clothes = {
			default = {
				shirt = "Sniper Wrap",
				pants = "Recon Pants",
				cape = false,
			},
			shadow = {
				shirt = "Ghillie Wrap",
				pants = "Stealth Pants",
				cape = true,
				capeColor = Color3.fromRGB(60, 80, 120),
				rarity = "Epic",
			},
		},
		powers = {
			quickScope = {name = "Quick Scope", description = "Instantly aim down sights with increased crit chance", critBonus = 0.3, duration = 3},
		},
		weaponSkin = "Chrome",
		killEffect = "Headshot",
	},

	-- === ASSAULT HEROES (continued) ===

	pyro_blazer = {
		id = "pyro_blazer",
		displayName = "Pyro Blazer",
		role = "Assault",
		maxHealth = 200,
		walkSpeed = 19,
		jumpPower = 44,
		weaponId = "flamethrower",
		abilityId = "fire_nova",
		ultimateId = "inferno",
		difficulty = 2,
		aiProfile = "Aggressive",
		primaryColor = Color3.fromRGB(255, 80, 20),
		secondaryColor = Color3.fromRGB(60, 20, 10),
		accentColor = Color3.fromRGB(255, 180, 50),
		shortDescription = "Area-denial assault hero wielding devastating fire.",
		lore = "Pyro Blazer turns the battlefield into a blazing inferno.",
		skins = {
			default = {
				bodyColor = Color3.fromRGB(255, 80, 20),
				shirtColor = Color3.fromRGB(80, 30, 10),
				pantsColor = Color3.fromRGB(60, 20, 5),
				helmet = true,
				visorColor = Color3.fromRGB(255, 150, 50),
				shoulderArmor = false,
			},
			infernal = {
				bodyColor = Color3.fromRGB(200, 40, 10),
				shirtColor = Color3.fromRGB(50, 10, 5),
				pantsColor = Color3.fromRGB(40, 8, 3),
				helmet = true,
				visorColor = Color3.fromRGB(255, 100, 20),
				shoulderArmor = true,
				rarity = "Legendary",
				emissive = true,
				glowColor = Color3.fromRGB(255, 60, 0),
			},
		},
		clothes = {
			default = {
				shirt = "Fire Jacket",
				pants = "Heat-Resistant Pants",
				cape = false,
			},
			heavy = {
				shirt = "Inferno Plate",
				pants = "Magma Greaves",
				cape = true,
				capeColor = Color3.fromRGB(180, 40, 0),
				rarity = "Epic",
			},
		},
		powers = {
			fireAura = {name = "Fire Aura", description = "Damages and ignites enemies that get too close", dps = 15, radius = 8},
		},
		weaponSkin = "Fire",
		killEffect = "Burning",
	},

	vector = {
		id = "vector",
		displayName = "Vector",
		role = "Assault",
		maxHealth = 165,
		walkSpeed = 24,
		jumpPower = 58,
		weaponId = "twin_pistols",
		abilityId = "adrenaline",
		ultimateId = "berserk",
		difficulty = 1,
		aiProfile = "Flanker",
		primaryColor = Color3.fromRGB(255, 255, 80),
		secondaryColor = Color3.fromRGB(40, 40, 40),
		accentColor = Color3.fromRGB(255, 220, 100),
		shortDescription = "Ultra-fast dual-pistol blitz fighter.",
		lore = "Speed is Vector's only law — strike fast, strike twice.",
		skins = {
			default = {
				bodyColor = Color3.fromRGB(255, 255, 80),
				shirtColor = Color3.fromRGB(50, 50, 50),
				pantsColor = Color3.fromRGB(35, 35, 40),
				helmet = false,
				visorColor = Color3.fromRGB(255, 255, 200),
				shoulderArmor = false,
			},
			golden = {
				bodyColor = Color3.fromRGB(255, 215, 0),
				shirtColor = Color3.fromRGB(60, 50, 10),
				pantsColor = Color3.fromRGB(45, 35, 5),
				helmet = true,
				visorColor = Color3.fromRGB(255, 255, 200),
				shoulderArmor = true,
				rarity = "Legendary",
			},
		},
		clothes = {
			default = {
				shirt = "Tactical Shirt",
				pants = "Sprint Pants",
				cape = false,
			},
			racer = {
				shirt = "Lightning Vest",
				pants = "Racing Pants",
				cape = false,
				rarity = "Rare",
			},
		},
		powers = {
			dashStrike = {name = "Dash Strike", description = "Every dash deals damage to enemies hit", damage = 30},
		},
		weaponSkin = "Neon",
		killEffect = "SparkBurst",
	},

	-- === FLANKER / ASSASSIN HEROES ===

	specter = {
		id = "specter",
		displayName = "Specter",
		role = "Assassin",
		maxHealth = 130,
		walkSpeed = 22,
		jumpPower = 55,
		weaponId = "shadow_smg",
		abilityId = "phase_dash",
		ultimateId = "cloak_and_dagger",
		difficulty = 3,
		aiProfile = "Assassin",
		primaryColor = Color3.fromRGB(140, 60, 200),
		secondaryColor = Color3.fromRGB(20, 10, 35),
		accentColor = Color3.fromRGB(200, 100, 255),
		shortDescription = "Stealth assassin with SMG and invisibility.",
		lore = "You'll never see Specter coming — by design.",
		skins = {
			default = {
				bodyColor = Color3.fromRGB(140, 60, 200),
				shirtColor = Color3.fromRGB(25, 10, 45),
				pantsColor = Color3.fromRGB(18, 8, 35),
				helmet = true,
				visorColor = Color3.fromRGB(220, 150, 255),
				shoulderArmor = false,
			},
			phantom = {
				bodyColor = Color3.fromRGB(80, 30, 140),
				shirtColor = Color3.fromRGB(10, 5, 20),
				pantsColor = Color3.fromRGB(8, 3, 15),
				helmet = true,
				visorColor = Color3.fromRGB(255, 200, 255),
				shoulderArmor = true,
				rarity = "Legendary",
				emissive = true,
				glowColor = Color3.fromRGB(150, 50, 255),
			},
		},
		clothes = {
			default = {
				shirt = "Stealth Suit",
				pants = "Shadow Trousers",
				cape = true,
				capeColor = Color3.fromRGB(50, 20, 80),
			},
			night = {
				shirt = "Night Cloak",
				pants = "Dark Infiltrator Pants",
				cape = true,
				capeColor = Color3.fromRGB(20, 5, 40),
				rarity = "Epic",
			},
		},
		powers = {
			vanish = {name = "Vanish", description = "Become invisible for a duration", duration = 4},
		},
		weaponSkin = "Neon",
		killEffect = "ShadowKill",
	},

	-- === CONTROLLER / MAGE HEROES ===

	cryomancer = {
		id = "cryomancer",
		displayName = "Cryomancer",
		role = "Controller",
		maxHealth = 130,
		walkSpeed = 18,
		jumpPower = 46,
		weaponId = "cryo_rifle",
		abilityId = "freeze_nova",
		ultimateId = "blizzard",
		difficulty = 3,
		aiProfile = "Controller",
		primaryColor = Color3.fromRGB(80, 200, 255),
		secondaryColor = Color3.fromRGB(15, 30, 60),
		accentColor = Color3.fromRGB(150, 230, 255),
		shortDescription = "Ice controller who freezes the battlefield.",
		lore = "Where Cryomancer walks, frost and despair follow.",
		skins = {
			default = {
				bodyColor = Color3.fromRGB(80, 200, 255),
				shirtColor = Color3.fromRGB(15, 35, 65),
				pantsColor = Color3.fromRGB(10, 25, 50),
				helmet = true,
				visorColor = Color3.fromRGB(180, 240, 255),
				shoulderArmor = false,
			},
			frostbitten = {
				bodyColor = Color3.fromRGB(40, 140, 220),
				shirtColor = Color3.fromRGB(8, 20, 45),
				pantsColor = Color3.fromRGB(5, 15, 35),
				helmet = true,
				visorColor = Color3.fromRGB(200, 255, 255),
				shoulderArmor = true,
				rarity = "Legendary",
				emissive = true,
				glowColor = Color3.fromRGB(50, 150, 255),
			},
		},
		clothes = {
			default = {
				shirt = "Arctic Robe",
				pants = "Frost Trousers",
				cape = true,
				capeColor = Color3.fromRGB(30, 80, 150),
			},
			glacial = {
				shirt = "Glacial Shroud",
				pants = "Ice Plate Legs",
				cape = true,
				capeColor = Color3.fromRGB(100, 180, 255),
				rarity = "Epic",
			},
		},
		powers = {
			iceWall = {name = "Ice Wall", description = "Creates an impassable wall of ice", duration = 6, health = 200},
		},
		weaponSkin = "Energy",
		killEffect = "FreezeShatter",
	},

	-- === SUPPORT / HEALER HEROES ===

	medic = {
		id = "medic",
		displayName = "Medic",
		role = "Support",
		maxHealth = 125,
		walkSpeed = 20,
		jumpPower = 48,
		weaponId = "bio_rifle",
		abilityId = "heal_pulse",
		ultimateId = "rejuvenation_field",
		difficulty = 2,
		aiProfile = "Support",
		primaryColor = Color3.fromRGB(80, 255, 140),
		secondaryColor = Color3.fromRGB(20, 60, 40),
		accentColor = Color3.fromRGB(120, 255, 180),
		shortDescription = "Dedicated healer keeping the team alive.",
		lore = "Medic's oath: no one dies on my watch.",
		skins = {
			default = {
				bodyColor = Color3.fromRGB(80, 255, 140),
				shirtColor = Color3.fromRGB(15, 50, 30),
				pantsColor = Color3.fromRGB(10, 40, 25),
				helmet = false,
				visorColor = Color3.fromRGB(180, 255, 220),
				shoulderArmor = false,
			},
			saint = {
				bodyColor = Color3.fromRGB(180, 255, 220),
				shirtColor = Color3.fromRGB(30, 60, 50),
				pantsColor = Color3.fromRGB(20, 50, 40),
				helmet = true,
				visorColor = Color3.fromRGB(255, 255, 240),
				shoulderArmor = true,
				hasWings = true,
				rarity = "Legendary",
			},
		},
		clothes = {
			default = {
				shirt = "Medic Jacket",
				pants = "Field Medic Pants",
				cape = false,
			},
			holy = {
				shirt = "Priest Robe",
				pants = "White Trousers",
				cape = true,
				capeColor = Color3.fromRGB(255, 255, 200),
				rarity = "Epic",
			},
		},
		powers = {
			revive = {name = "Revive", description = "Instantly revive a downed ally within range", range = 20},
		},
		weaponSkin = "Neon",
		killEffect = "HealBurst",
	},

	-- === BRAWLER / OFFENSIVE HEROES ===

	berserker = {
		id = "berserker",
		displayName = "Berserker",
		role = "Brawler",
		maxHealth = 350,
		walkSpeed = 17,
		jumpPower = 40,
		weaponId = "gravity_hammer",
		abilityId = "berserk",
		ultimateId = "blood_frenzy",
		difficulty = 2,
		aiProfile = "Frontline",
		primaryColor = Color3.fromRGB(200, 50, 50),
		secondaryColor = Color3.fromRGB(60, 15, 15),
		accentColor = Color3.fromRGB(255, 120, 80),
		shortDescription = "Brutal brawler with a gravity hammer and rage.",
		lore = "Berserker lives for the fight. Blood fuels his fury.",
		skins = {
			default = {
				bodyColor = Color3.fromRGB(200, 50, 50),
				shirtColor = Color3.fromRGB(60, 15, 15),
				pantsColor = Color3.fromRGB(45, 10, 10),
				helmet = true,
				visorColor = Color3.fromRGB(255, 150, 100),
				shoulderArmor = true,
			},
			crimson = {
				bodyColor = Color3.fromRGB(180, 20, 20),
				shirtColor = Color3.fromRGB(40, 5, 5),
				pantsColor = Color3.fromRGB(30, 3, 3),
				helmet = true,
				visorColor = Color3.fromRGB(255, 80, 40),
				shoulderArmor = true,
				rarity = "Legendary",
			},
		},
		clothes = {
			default = {
				shirt = "Warrior Chestplate",
				pants = "Battle Greaves",
				cape = false,
			},
			ancient = {
				shirt = "Ancient Armor",
				pants = "Ancient Greaves",
				cape = true,
				capeColor = Color3.fromRGB(180, 40, 20),
				rarity = "Legendary",
			},
		},
		powers = {
			bloodThirst = {name = "Blood Thirst", description = "Heal for a percentage of damage dealt", healPercent = 0.2},
		},
		weaponSkin = "Fire",
		killEffect = "GroundSlam",
	},

	-- === MAGE / ULTIMATE HEROES ===

	phoenix = {
		id = "phoenix",
		displayName = "Phoenix",
		role = "Mage",
		maxHealth = 140,
		walkSpeed = 20,
		jumpPower = 52,
		weaponId = "plasma_caster",
		abilityId = "phoenix_dive",
		ultimateId = "supernova",
		difficulty = 3,
		aiProfile = "Backline",
		primaryColor = Color3.fromRGB(255, 140, 30),
		secondaryColor = Color3.fromRGB(80, 20, 10),
		accentColor = Color3.fromRGB(255, 200, 80),
		shortDescription = "Reborn fire mage with explosive dive attack.",
		lore = "Phoenix rises from ashes, burning brighter with each rebirth.",
		skins = {
			default = {
				bodyColor = Color3.fromRGB(255, 140, 30),
				shirtColor = Color3.fromRGB(80, 30, 10),
				pantsColor = Color3.fromRGB(60, 20, 5),
				helmet = false,
				visorColor = Color3.fromRGB(255, 200, 100),
				shoulderArmor = false,
			},
			solar = {
				bodyColor = Color3.fromRGB(255, 100, 0),
				shirtColor = Color3.fromRGB(60, 10, 0),
				pantsColor = Color3.fromRGB(50, 8, 0),
				helmet = true,
				visorColor = Color3.fromRGB(255, 220, 150),
				shoulderArmor = true,
				rarity = "Legendary",
				emissive = true,
				glowColor = Color3.fromRGB(255, 150, 0),
			},
		},
		clothes = {
			default = {
				shirt = "Phoenix Robe",
				pants = "Ember Trousers",
				cape = true,
				capeColor = Color3.fromRGB(180, 60, 0),
			},
			infernal = {
				shirt = "Solar Shroud",
				pants = "Magma Wraps",
				cape = true,
				capeColor = Color3.fromRGB(255, 80, 0),
				rarity = "Epic",
			},
		},
		powers = {
			rebirth = {name = "Rebirth", description = "Revive with partial health after being killed", healthPercent = 0.3, cooldown = 120},
		},
		weaponSkin = "Energy",
		killEffect = "PlasmaExplode",
	},
}

return HeroConfig