--!strict

-- Pulse Deck Arena - Hero Configuration
-- Each hero has unique stats, weapons, abilities, cosmetics, and powers

local HeroConfig = {

	-- === ASSAULT HEROES ===

	bolt_runner = {
		id = "bolt_runner",
		displayName = "Bolt Runner",
		role = "Assault",
		maxHealth = 150,
		walkSpeed = 22,
		jumpPower = 55,
		weaponId = "pulse_rifle",
		abilityId = "phase_dash",
		ultimateId = "ultimate_ability",
		difficulty = 1,
		aiProfile = "Flanker",
		primaryColor = Color3.fromRGB(255, 222, 35),
		secondaryColor = Color3.fromRGB(35, 35, 40),
		accentColor = Color3.fromRGB(255, 180, 0),
		shortDescription = "Mobile rifle duelist with a quick dash.",
		lore = "Fastest scout in the arena, striking with precision and speed.",
		-- Cosmetics / Skin
		skins = {
			default = {
				bodyColor = Color3.fromRGB(255, 222, 35),
				shirtColor = Color3.fromRGB(40, 40, 50),
				pantsColor = Color3.fromRGB(30, 30, 38),
				helmet = true,
				visorColor = Color3.fromRGB(200, 255, 255),
				shoulderArmor = false,
			},
			gold = {
				bodyColor = Color3.fromRGB(255, 215, 0),
				shirtColor = Color3.fromRGB(60, 50, 20),
				pantsColor = Color3.fromRGB(40, 35, 15),
				helmet = true,
				visorColor = Color3.fromRGB(255, 255, 200),
				shoulderArmor = true,
				rarity = "Legendary",
			},
			shadow = {
				bodyColor = Color3.fromRGB(60, 60, 70),
				shirtColor = Color3.fromRGB(20, 20, 25),
				pantsColor = Color3.fromRGB(15, 15, 20),
				helmet = true,
				visorColor = Color3.fromRGB(255, 50, 50),
				shoulderArmor = false,
				rarity = "Epic",
			},
		},
		-- Clothing
		clothes = {
			default = {
				shirt = "Classic Tee",
				pants = "Tactical Pants",
				cape = false,
			},
			armored = {
				shirt = "Heavy Vest",
				pants = "Reinforced Trousers",
				cape = false,
				rarity = "Rare",
			},
		},
		-- Powers
		powers = {
			speedBoost = {name = "Speed Boost", description = "Temporarily increases movement speed", multiplier = 1.3, duration = 3},
		},
		weaponSkin = "Default",
		killEffect = "ElectricShock",
	},

	iron_bulwark = {
		id = "iron_bulwark",
		displayName = "Iron Bulwark",
		role = "Tank",
		maxHealth = 300,
		walkSpeed = 14,
		jumpPower = 42,
		weaponId = "scatter_cannon",
		abilityId = "shield_dome",
		ultimateId = "fortify",
		difficulty = 2,
		aiProfile = "Frontline",
		primaryColor = Color3.fromRGB(128, 136, 145),
		secondaryColor = Color3.fromRGB(255, 128, 35),
		accentColor = Color3.fromRGB(80, 90, 100),
		shortDescription = "Heavy frontliner with shotgun pressure and dome shield.",
		lore = "An immovable fortress, crushing all who dare stand against him.",
		skins = {
			default = {
				bodyColor = Color3.fromRGB(128, 136, 145),
				shirtColor = Color3.fromRGB(60, 65, 70),
				pantsColor = Color3.fromRGB(50, 55, 60),
				helmet = true,
				visorColor = Color3.fromRGB(200, 200, 210),
				shoulderArmor = true,
			},
			titanium = {
				bodyColor = Color3.fromRGB(180, 190, 200),
				shirtColor = Color3.fromRGB(40, 45, 55),
				pantsColor = Color3.fromRGB(35, 40, 50),
				helmet = true,
				visorColor = Color3.fromRGB(150, 200, 255),
				shoulderArmor = true,
				rarity = "Legendary",
				metalness = 1.0,
			},
			rustLord = {
				bodyColor = Color3.fromRGB(160, 120, 60),
				shirtColor = Color3.fromRGB(80, 50, 20),
				pantsColor = Color3.fromRGB(60, 35, 10),
				helmet = true,
				visorColor = Color3.fromRGB(255, 180, 50),
				shoulderArmor = true,
				rarity = "Epic",
			},
		},
		clothes = {
			default = {
				shirt = "Plate Carrier",
				pants = "Heavy Armor Pants",
				cape = false,
			},
			royal = {
				shirt = "Royal Guard Vest",
				pants = "Royal Greaves",
				cape = true,
				capeColor = Color3.fromRGB(200, 50, 50),
				rarity = "Legendary",
			},
		},
		powers = {
			damageResistance = {name = "Damage Resistance", description = "Reduces all incoming damage", reduction = 0.15, duration = 5},
		},
		weaponSkin = "Chrome",
		killEffect = "GroundSlam",
	},

	-- === SNIPER HEROES ===

	vesper_scope = {
		id = "vesper_scope",
		displayName = "Vesper Scope",
		role = "Sniper",
		maxHealth = 110,
		walkSpeed = 16,
		jumpPower = 45,
		weaponId = "rail_lance",
		abilityId = "tracker_mark",
		ultimateId = "time_dilation",
		difficulty = 3,
		aiProfile = "Backline",
		primaryColor = Color3.fromRGB(150, 75, 255),
		secondaryColor = Color3.fromRGB(15, 15, 20),
		accentColor = Color3.fromRGB(200, 150, 255),
		shortDescription = "Long-range precision hero that marks enemies.",
		lore = "No one escapes the gaze of Vesper. Every shot finds its mark.",
		skins = {
			default = {
				bodyColor = Color3.fromRGB(150, 75, 255),
				shirtColor = Color3.fromRGB(30, 20, 50),
				pantsColor = Color3.fromRGB(25, 15, 45),
				helmet = true,
				visorColor = Color3.fromRGB(180, 120, 255),
				shoulderArmor = false,
			},
			cosmic = {
				bodyColor = Color3.fromRGB(80, 40, 140),
				shirtColor = Color3.fromRGB(10, 5, 20),
				pantsColor = Color3.fromRGB(8, 3, 15),
				helmet = true,
				visorColor = Color3.fromRGB(255, 200, 255),
				shoulderArmor = true,
				rarity = "Legendary",
				emissive = true,
				glowColor = Color3.fromRGB(100, 50, 200),
			},
		},
		clothes = {
			default = {
				shirt = "Sniper Cloak",
				pants = "Stealth Trousers",
				cape = true,
				capeColor = Color3.fromRGB(80, 40, 120),
			},
		},
		powers = {
			wallHack = {name = "Wall Hack", description = "Enemies become visible through walls", duration = 4},
		},
		weaponSkin = "Camo",
		killEffect = "Disintegration",
	},

	-- === SUPPORT HEROES ===

	patch_flux = {
		id = "patch_flux",
		displayName = "Patch Flux",
		role = "Support",
		maxHealth = 140,
		walkSpeed = 19,
		jumpPower = 48,
		weaponId = "nano_smg",
		abilityId = "heal_pulse",
		ultimateId = "rejuvenation_field",
		difficulty = 2,
		aiProfile = "Support",
		primaryColor = Color3.fromRGB(92, 255, 180),
		secondaryColor = Color3.fromRGB(245, 245, 245),
		accentColor = Color3.fromRGB(50, 255, 150),
		shortDescription = "Fast support who heals allies and chips enemies.",
		lore = "The heart of any team, keeping everyone alive with nanotech mastery.",
		skins = {
			default = {
				bodyColor = Color3.fromRGB(92, 255, 180),
				shirtColor = Color3.fromRGB(20, 50, 45),
				pantsColor = Color3.fromRGB(15, 40, 35),
				helmet = false,
				visorColor = Color3.fromRGB(150, 255, 220),
				shoulderArmor = false,
			},
			angel = {
				bodyColor = Color3.fromRGB(200, 255, 230),
				shirtColor = Color3.fromRGB(30, 40, 60),
				pantsColor = Color3.fromRGB(25, 35, 55),
				helmet = true,
				visorColor = Color3.fromRGB(255, 255, 200),
				shoulderArmor = true,
				hasWings = true,
				rarity = "Legendary",
			},
		},
		clothes = {
			default = {
				shirt = "Medic Jacket",
				pants = "Combat Medic Pants",
				cape = false,
			},
			holy = {
				shirt = "Priest Robe",
				pants = "White Trousers",
				cape = true,
				capeColor = Color3.fromRGB(255, 255, 200),
				rarity = "Epic",
			},
		},
		powers = {
			teamHeal = {name = "Team Heal", description = "Instantly heal all nearby allies", amount = 30, radius = 20},
		},
		weaponSkin = "Neon",
		killEffect = "HealBurst",
	},

	fuse_jack = {
		id = "fuse_jack",
		displayName = "Fuse Jack",
		role = "Demolition",
		maxHealth = 165,
		walkSpeed = 17,
		jumpPower = 48,
		weaponId = "arc_launcher",
		abilityId = "cluster_charge",
		ultimateId = "thermal_grenade",
		difficulty = 2,
		aiProfile = "Siege",
		primaryColor = Color3.fromRGB(255, 82, 36),
		secondaryColor = Color3.fromRGB(95, 58, 35),
		accentColor = Color3.fromRGB(255, 140, 50),
		shortDescription = "Explosive objective breaker with splash damage.",
		lore = "Where Fuse Jack goes, explosions follow. Boom is his language.",
		skins = {
			default = {
				bodyColor = Color3.fromRGB(255, 82, 36),
				shirtColor = Color3.fromRGB(60, 30, 15),
				pantsColor = Color3.fromRGB(50, 25, 10),
				helmet = false,
				visorColor = Color3.fromRGB(255, 200, 100),
				shoulderArmor = false,
			},
			pyro = {
				bodyColor = Color3.fromRGB(200, 50, 20),
				shirtColor = Color3.fromRGB(40, 15, 5),
				pantsColor = Color3.fromRGB(30, 10, 5),
				helmet = true,
				visorColor = Color3.fromRGB(255, 100, 30),
				shoulderArmor = true,
				rarity = "Epic",
			},
		},
		clothes = {
			default = {
				shirt = "Demolition Vest",
				pants = "Cargo Combat Pants",
				cape = false,
			},
			heavy = {
				shirt = "Explosive Expert Jacket",
				pants = "Reinforced Demolition Pants",
				cape = false,
				rarity = "Rare",
			},
		},
		powers = {
			blastWave = {name = "Blast Wave", description = "Creates a shockwave that knocks back all nearby enemies", radius = 15, force = 70},
		},
		weaponSkin = "Fire",
		killEffect = "BigExplosion",
	},

	-- === SKIRMISHER HEROES ===

	glitch_byte = {
		id = "glitch_byte",
		displayName = "Glitch Byte",
		role = "Skirmisher",
		maxHealth = 130,
		walkSpeed = 23,
		jumpPower = 58,
		weaponId = "phase_smg",
		abilityId = "blink_swap",
		ultimateId = "nova_burst",
		difficulty = 3,
		aiProfile = "Assassin",
		primaryColor = Color3.fromRGB(255, 45, 210),
		secondaryColor = Color3.fromRGB(10, 10, 16),
		accentColor = Color3.fromRGB(255, 100, 255),
		shortDescription = "High mobility ambusher with short teleport.",
		lore = "A digital phantom, appearing and disappearing in the blink of an eye.",
		skins = {
			default = {
				bodyColor = Color3.fromRGB(255, 45, 210),
				shirtColor = Color3.fromRGB(20, 5, 35),
				pantsColor = Color3.fromRGB(15, 3, 25),
				helmet = false,
				visorColor = Color3.fromRGB(255, 150, 255),
				shoulderArmor = false,
			},
			digital = {
				bodyColor = Color3.fromRGB(180, 30, 160),
				shirtColor = Color3.fromRGB(10, 10, 15),
				pantsColor = Color3.fromRGB(5, 5, 10),
				helmet = true,
				visorColor = Color3.fromRGB(0, 255, 200),
				shoulderArmor = false,
				rarity = "Epic",
				emissive = true,
				glowColor = Color3.fromRGB(100, 0, 255),
			},
		},
		clothes = {
			default = {
				shirt = "Hacker Jacket",
				pants = "Cyber Pants",
				cape = false,
			},
			stealth = {
				shirt = "Shadow Cloak",
				pants = "Dark Trousers",
				cape = true,
				capeColor = Color3.fromRGB(40, 0, 60),
				rarity = "Rare",
			},
		},
		powers = {
			phaseCloak = {name = "Phase Cloak", description = "Become invisible for a short duration", duration = 2.5},
		},
		weaponSkin = "Neon",
		killEffect = "GlitchExplode",
	},

	-- === ENGINEER HEROES ===

	terra_pin = {
		id = "terra_pin",
		displayName = "Terra Pin",
		role = "Engineer",
		maxHealth = 160,
		walkSpeed = 18,
		jumpPower = 45,
		weaponId = "rivet_carbine",
		abilityId = "mini_sentry",
		ultimateId = "smart_mine",
		difficulty = 2,
		aiProfile = "Defender",
		primaryColor = Color3.fromRGB(204, 174, 120),
		secondaryColor = Color3.fromRGB(35, 180, 170),
		accentColor = Color3.fromRGB(220, 200, 100),
		shortDescription = "Defensive engineer who deploys a temporary sentry turret.",
		lore = "Master engineer Terra Pin builds deadly automated defenses.",
		skins = {
			default = {
				bodyColor = Color3.fromRGB(204, 174, 120),
				shirtColor = Color3.fromRGB(50, 60, 70),
				pantsColor = Color3.fromRGB(40, 50, 60),
				helmet = true,
				visorColor = Color3.fromRGB(150, 220, 200),
				shoulderArmor = false,
			},
			mechTech = {
				bodyColor = Color3.fromRGB(180, 160, 100),
				shirtColor = Color3.fromRGB(30, 40, 50),
				pantsColor = Color3.fromRGB(25, 35, 45),
				helmet = true,
				visorColor = Color3.fromRGB(100, 255, 200),
				shoulderArmor = true,
				rarity = "Rare",
			},
		},
		clothes = {
			default = {
				shirt = "Engineer Jacket",
				pants = "Work Pants",
				cape = false,
			},
			tactical = {
				shirt = "Tactical Harness",
				pants = "Camo Pants",
				cape = false,
				rarity = "Rare",
			},
		},
		powers = {
			barrier = {name = "Barrier", description = "Place a temporary health barrier on any surface", health = 100, duration = 8},
		},
		weaponSkin = "Woodland",
		killEffect = "TurretKill",
	},

	-- === CONTROLLER HEROES ===

	wisp_ion = {
		id = "wisp_ion",
		displayName = "Wisp Ion",
		role = "Controller",
		maxHealth = 135,
		walkSpeed = 19,
		jumpPower = 52,
		weaponId = "ion_beam",
		abilityId = "slow_field",
		ultimateId = "energy_shield",
		difficulty = 2,
		aiProfile = "Controller",
		primaryColor = Color3.fromRGB(55, 230, 255),
		secondaryColor = Color3.fromRGB(170, 80, 255),
		accentColor = Color3.fromRGB(100, 255, 255),
		shortDescription = "Beam controller who slows grouped enemies.",
		lore = "Commander of the ethereal, bending energy to his will.",
		skins = {
			default = {
				bodyColor = Color3.fromRGB(55, 230, 255),
				shirtColor = Color3.fromRGB(20, 40, 80),
				pantsColor = Color3.fromRGB(15, 30, 60),
				helmet = true,
				visorColor = Color3.fromRGB(150, 255, 255),
				shoulderArmor = false,
			},
			nebula = {
				bodyColor = Color3.fromRGB(100, 50, 200),
				shirtColor = Color3.fromRGB(15, 10, 30),
				pantsColor = Color3.fromRGB(10, 5, 20),
				helmet = true,
				visorColor = Color3.fromRGB(200, 150, 255),
				shoulderArmor = true,
				rarity = "Legendary",
				emissive = true,
				glowColor = Color3.fromRGB(80, 0, 255),
			},
		},
		clothes = {
			default = {
				shirt = "Energy Harness",
				pants = "Plasma Trousers",
				cape = true,
				capeColor = Color3.fromRGB(40, 100, 200),
			},
		},
		powers = {
			energyDrain = {name = "Energy Drain", description = "Drains health from nearby enemies over time", dps = 10, radius = 12, duration = 4},
		},
		weaponSkin = "Energy",
		killEffect = "EnergyBurst",
	},

	-- === NEW HEROES ===

	reaper = {
		id = "reaper",
		displayName = "Reaper",
		role = "Flanker",
		maxHealth = 175,
		walkSpeed = 21,
		jumpPower = 50,
		weaponId = "shotgun",
		abilityId = "shadow_step",
		ultimateId = "gravity_well",
		difficulty = 2,
		aiProfile = "Flanker",
		primaryColor = Color3.fromRGB(45, 45, 55),
		secondaryColor = Color3.fromRGB(180, 50, 50),
		accentColor = Color3.fromRGB(80, 80, 100),
		shortDescription = "Close-range terror with shadow teleport.",
		lore = "Death walks silently through the shadows.",
		skins = {
			default = {
				bodyColor = Color3.fromRGB(45, 45, 55),
				shirtColor = Color3.fromRGB(25, 25, 30),
				pantsColor = Color3.fromRGB(20, 20, 25),
				helmet = true,
				visorColor = Color3.fromRGB(255, 80, 80),
				shoulderArmor = false,
			},
			death = {
				bodyColor = Color3.fromRGB(30, 30, 35),
				shirtColor = Color3.fromRGB(10, 10, 15),
				pantsColor = Color3.fromRGB(5, 5, 10),
				helmet = true,
				visorColor = Color3.fromRGB(255, 30, 30),
				shoulderArmor = true,
				rarity = "Legendary",
			},
		},
		clothes = {
			default = {
				shirt = "Reaper Hoodie",
				pants = "Dark Combat Pants",
				cape = true,
				capeColor = Color3.fromRGB(30, 30, 40),
			},
		},
		powers = {
			lifeDrain = {name = "Life Drain", description = "Melee kills restore health", amount = 25},
		},
		weaponSkin = "Dark",
		killEffect = "ShadowKill",
	},

	chrono = {
		id = "chrono",
		displayName = "Chrono",
		role = "Controller",
		maxHealth = 125,
		walkSpeed = 17,
		jumpPower = 48,
		weaponId = "vortex_rifle",
		abilityId = "time_dilation",
		ultimateId = "overcharge",
		difficulty = 3,
		aiProfile = "Controller",
		primaryColor = Color3.fromRGB(80, 130, 255),
		secondaryColor = Color3.fromRGB(20, 30, 60),
		accentColor = Color3.fromRGB(150, 200, 255),
		shortDescription = "Time-bending strategist with devastating charged shots.",
		lore = "Master of temporal manipulation, Chrono controls the flow of battle.",
		skins = {
			default = {
				bodyColor = Color3.fromRGB(80, 130, 255),
				shirtColor = Color3.fromRGB(15, 25, 50),
				pantsColor = Color3.fromRGB(10, 20, 40),
				helmet = true,
				visorColor = Color3.fromRGB(180, 220, 255),
				shoulderArmor = false,
			},
			temporal = {
				bodyColor = Color3.fromRGB(50, 80, 180),
				shirtColor = Color3.fromRGB(5, 10, 30),
				pantsColor = Color3.fromRGB(3, 8, 20),
				helmet = true,
				visorColor = Color3.fromRGB(200, 230, 255),
				shoulderArmor = true,
				rarity = "Legendary",
				emissive = true,
				glowColor = Color3.fromRGB(50, 100, 255),
			},
		},
		clothes = {
			default = {
				shirt = "Time Keeper Robe",
				pants = "Temporal Pants",
				cape = true,
				capeColor = Color3.fromRGB(40, 60, 150),
			},
		},
		powers = {
			timeFreeze = {name = "Time Freeze", description = "Briefly freezes all enemies in an area", radius = 12, duration = 2},
		},
		weaponSkin = "Chrome",
		killEffect = "TimeSnap",
	},

	nova = {
		id = "nova",
		displayName = "Nova",
		role = "Mage",
		maxHealth = 120,
		walkSpeed = 18,
		jumpPower = 50,
		weaponId = "plasma_caster",
		abilityId = "nova_burst",
		ultimateId = "overcharge",
		difficulty = 3,
		aiProfile = "Backline",
		primaryColor = Color3.fromRGB(255, 80, 180),
		secondaryColor = Color3.fromRGB(40, 15, 60),
		accentColor = Color3.fromRGB(255, 150, 220),
		shortDescription = "Devastating plasma mage with area control.",
		lore = "Raw plasma energy courses through Nova's veins.",
		skins = {
			default = {
				bodyColor = Color3.fromRGB(255, 80, 180),
				shirtColor = Color3.fromRGB(50, 10, 40),
				pantsColor = Color3.fromRGB(40, 5, 30),
				helmet = false,
				visorColor = Color3.fromRGB(255, 200, 255),
				shoulderArmor = false,
			},
			stellar = {
				bodyColor = Color3.fromRGB(200, 50, 150),
				shirtColor = Color3.fromRGB(30, 5, 25),
				pantsColor = Color3.fromRGB(20, 3, 15),
				helmet = true,
				visorColor = Color3.fromRGB(255, 150, 255),
				shoulderArmor = true,
				rarity = "Legendary",
				emissive = true,
				glowColor = Color3.fromRGB(255, 50, 200),
			},
		},
		clothes = {
			default = {
				shirt = "Mage Robe",
				pants = "Mystic Trousers",
				cape = true,
				capeColor = Color3.fromRGB(180, 30, 100),
			},
		},
		powers = {
			plasmaShield = {name = "Plasma Shield", description = "Absorb incoming damage as energy", maxShield = 100, duration = 5},
		},
		weaponSkin = "Energy",
		killEffect = "PlasmaExplode",
	},

	bastion = {
		id = "bastion",
		displayName = "Bastion",
		role = "Defender",
		maxHealth = 320,
		walkSpeed = 13,
		jumpPower = 40,
		weaponId = "gravity_hammer",
		abilityId = "energy_shield",
		ultimateId = "fortify",
		difficulty = 2,
		aiProfile = "Frontline",
		primaryColor = Color3.fromRGB(200, 100, 50),
		secondaryColor = Color3.fromRGB(60, 30, 15),
		accentColor = Color3.fromRGB(255, 150, 80),
		shortDescription = "Immovable fortress with devastating hammer.",
		lore = "The last line of defense. Nothing gets past Bastion.",
		skins = {
			default = {
				bodyColor = Color3.fromRGB(200, 100, 50),
				shirtColor = Color3.fromRGB(50, 25, 10),
				pantsColor = Color3.fromRGB(40, 20, 8),
				helmet = true,
				visorColor = Color3.fromRGB(255, 200, 150),
				shoulderArmor = true,
			},
			ironclad = {
				bodyColor = Color3.fromRGB(160, 80, 30),
				shirtColor = Color3.fromRGB(30, 15, 5),
				pantsColor = Color3.fromRGB(20, 10, 3),
				helmet = true,
				visorColor = Color3.fromRGB(255, 180, 100),
				shoulderArmor = true,
				rarity = "Epic",
			},
		},
		clothes = {
			default = {
				shirt = "Warrior Chestplate",
				pants = "Battle Greaves",
				cape = false,
			},
			ancient = {
				shirt = "Ancient Armor",
				pants = "Ancient Greaves",
				cape = true,
				capeColor = Color3.fromRGB(180, 80, 30),
				rarity = "Legendary",
			},
		},
		powers = {
			groundSlam = {name = "Ground Slam", description = "Stuns all enemies in radius", radius = 14, stunDuration = 2},
		},
		weaponSkin = "Fire",
		killEffect = "HammerSlam",
	},
}

return HeroConfig