--!strict

-- Pulse Deck Arena - Weapon Configuration
-- Each weapon defines its behavior, damage model, visual properties, and stats

local WeaponConfig = {

	-- === ASSAULT WEAPONS ===

	pulse_rifle = {
		id = "pulse_rifle",
		displayName = "Pulse Rifle",
		description = "Balanced automatic energy rifle. Reliable all-rounder.",
		rarity = "Common",
		behavior = "HitscanAuto",
		damage = 14,
		headMultiplier = 1.4,
		fireInterval = 0.105,
		range = 420,
		spreadDegrees = 1.6,
		magazineSize = 30,
		reserveAmmo = 90,
		reloadTime = 1.45,
		falloffStart = 150,
		falloffEnd = 360,
		falloffMultiplierAtEnd = 0.65,
		tracerColor = Color3.fromRGB(255, 230, 45),
		muzzleFlashColor = Color3.fromRGB(255, 200, 50),
		weaponModel = "Rifle",
		recoil = 0.8,
		sprintSpeedMultiplier = 0.85,
	},

	scatter_cannon = {
		id = "scatter_cannon",
		displayName = "Scatter Cannon",
		description = "Close-range devastation. 8 pellets per shot.",
		rarity = "Common",
		behavior = "Shotgun",
		pellets = 8,
		damagePerPellet = 8,
		fireInterval = 0.78,
		range = 135,
		spreadDegrees = 7.5,
		magazineSize = 6,
		reserveAmmo = 30,
		reloadTime = 2.0,
		knockback = 35,
		tracerColor = Color3.fromRGB(255, 145, 40),
		muzzleFlashColor = Color3.fromRGB(255, 120, 30),
		weaponModel = "Shotgun",
		recoil = 1.5,
		sprintSpeedMultiplier = 0.9,
	},

	nano_smg = {
		id = "nano_smg",
		displayName = "Nano SMG",
		description = "Ultra-fast fire rate, low damage per shot. Spray and pray.",
		rarity = "Common",
		behavior = "HitscanAuto",
		damage = 8,
		headMultiplier = 1.25,
		fireInterval = 0.065,
		range = 260,
		spreadDegrees = 2.8,
		magazineSize = 42,
		reserveAmmo = 126,
		reloadTime = 1.55,
		falloffStart = 100,
		falloffEnd = 240,
		falloffMultiplierAtEnd = 0.7,
		tracerColor = Color3.fromRGB(95, 255, 180),
		muzzleFlashColor = Color3.fromRGB(80, 255, 160),
		weaponModel = "SMG",
		recoil = 0.4,
		sprintSpeedMultiplier = 0.9,
	},

	phase_smg = {
		id = "phase_smg",
		displayName = "Phase SMG",
		description = "Burst-fire energy submachine gun.",
		rarity = "Uncommon",
		behavior = "BurstHitscan",
		damage = 9,
		headMultiplier = 1.25,
		burstCount = 3,
		burstInterval = 0.045,
		fireInterval = 0.24,
		range = 280,
		spreadDegrees = 2.2,
		magazineSize = 36,
		reserveAmmo = 108,
		reloadTime = 1.6,
		tracerColor = Color3.fromRGB(255, 50, 220),
		muzzleFlashColor = Color3.fromRGB(200, 30, 180),
		weaponModel = "SMG",
		recoil = 0.6,
		sprintSpeedMultiplier = 0.88,
	},

	rivet_carbine = {
		id = "rivet_carbine",
		displayName = "Rivet Carbine",
		description = "Precise semi-auto with solid damage.",
		rarity = "Common",
		behavior = "SemiHitscan",
		damage = 21,
		headMultiplier = 1.35,
		fireInterval = 0.22,
		range = 390,
		spreadDegrees = 1.1,
		magazineSize = 18,
		reserveAmmo = 54,
		reloadTime = 1.75,
		tracerColor = Color3.fromRGB(40, 210, 200),
		muzzleFlashColor = Color3.fromRGB(30, 180, 170),
		weaponModel = "Carbine",
		recoil = 1.0,
		sprintSpeedMultiplier = 0.9,
	},

	-- === SNIPER WEAPONS ===

	rail_lance = {
		id = "rail_lance",
		displayName = "Rail Lance",
		description = "Heavy sniper. Pierces through enemies.",
		rarity = "Rare",
		behavior = "HitscanSniper",
		damage = 82,
		headMultiplier = 1.6,
		fireInterval = 1.15,
		range = 800,
		spreadDegrees = 0.15,
		magazineSize = 5,
		reserveAmmo = 15,
		reloadTime = 2.25,
		pierceCount = 2,
		scopedFov = 38,
		unscopedFov = 70,
		tracerColor = Color3.fromRGB(170, 85, 255),
		muzzleFlashColor = Color3.fromRGB(140, 60, 230),
		weaponModel = "Sniper",
		recoil = 2.5,
		sprintSpeedMultiplier = 0.75,
	},

	vortex_rifle = {
		id = "vortex_rifle",
		displayName = "Vortex Rifle",
		description = "Charged sniper shot that pulls enemies inward.",
		rarity = "Legendary",
		behavior = "ChargedSniper",
		baseDamage = 60,
		maxDamage = 120,
		chargeTime = 1.5,
		headMultiplier = 1.5,
		fireInterval = 1.8,
		range = 900,
		spreadDegrees = 0.1,
		magazineSize = 4,
		reserveAmmo = 12,
		reloadTime = 2.5,
		pierceCount = 1,
		scopedFov = 40,
		tracerColor = Color3.fromRGB(100, 200, 255),
		muzzleFlashColor = Color3.fromRGB(80, 180, 255),
		weaponModel = "Sniper",
		recoil = 2.0,
		sprintSpeedMultiplier = 0.78,
	},

	-- === EXPLOSIVE WEAPONS ===

	arc_launcher = {
		id = "arc_launcher",
		displayName = "Arc Launcher",
		description = "Rocket launcher with devastating splash damage.",
		rarity = "Uncommon",
		behavior = "ProjectileExplosive",
		directDamage = 48,
		splashDamage = 42,
		splashRadius = 18,
		projectileSpeed = 175,
		fireInterval = 0.9,
		rangeLifetime = 4,
		magazineSize = 5,
		reserveAmmo = 15,
		reloadTime = 2.35,
		selfDamageMultiplier = 0.35,
		tracerColor = Color3.fromRGB(255, 90, 38),
		muzzleFlashColor = Color3.fromRGB(255, 70, 20),
		explosionEffect = true,
		weaponModel = "Launcher",
		recoil = 2.0,
		sprintSpeedMultiplier = 0.85,
	},

	cluster_mortar = {
		id = "cluster_mortar",
		displayName = "Cluster Mortar",
		description = "High-arcing mortar that splits into bomblets.",
		rarity = "Rare",
		behavior = "ProjectileCluster",
		directDamage = 35,
		splashDamage = 28,
		splashRadius = 14,
		projectileSpeed = 120,
		arcHeight = 40,
		fireInterval = 1.4,
		rangeLifetime = 3.5,
		magazineSize = 4,
		reserveAmmo = 12,
		reloadTime = 2.8,
		selfDamageMultiplier = 0.2,
		subMunitions = 6,
		subDamage = 12,
		subRadius = 7,
		tracerColor = Color3.fromRGB(200, 120, 40),
		muzzleFlashColor = Color3.fromRGB(180, 90, 20),
		weaponModel = "Mortar",
		recoil = 1.5,
		sprintSpeedMultiplier = 0.85,
	},

	thermal_grenade = {
		id = "thermal_grenade",
		displayName = "Thermal Grenade",
		description = "Sticky grenade that creates a burning area.",
		rarity = "Rare",
		behavior = "StickyGrenade",
		directDamage = 55,
		splashDamage = 35,
		splashRadius = 15,
		fireInterval = 0.9,
		magazineSize = 2,
		reserveAmmo = 8,
		reloadTime = 2.0,
		fuseTime = 1.8,
		burnDuration = 4,
		burnDamagePerTick = 8,
		burnTickInterval = 0.5,
		stickRadius = 5,
		tracerColor = Color3.fromRGB(255, 160, 40),
		muzzleFlashColor = Color3.fromRGB(255, 100, 20),
		weaponModel = "GrenadeLauncher",
		recoil = 1.0,
		sprintSpeedMultiplier = 0.9,
	},

	-- === ENERGY WEAPONS ===

	ion_beam = {
		id = "ion_beam",
		displayName = "Ion Beam",
		description = "Continuous beam that drains ammo over time.",
		rarity = "Rare",
		behavior = "Beam",
		damagePerSecond = 52,
		tickInterval = 0.1,
		range = 190,
		beamWidth = 2.5,
		magazineSize = 100,
		ammoDrainPerSecond = 18,
		reloadTime = 1.9,
		tracerColor = Color3.fromRGB(60, 235, 255),
		muzzleFlashColor = Color3.fromRGB(40, 220, 255),
		weaponModel = "Beam",
		recoil = 0.3,
		sprintSpeedMultiplier = 0.8,
	},

	plasma_caster = {
		id = "plasma_caster",
		displayName = "Plasma Caster",
		description = "Charging energy weapon. Release for explosive plasma bolt.",
		rarity = "Epic",
		behavior = "ChargingProjectile",
		minDamage = 20,
		maxDamage = 65,
		chargeTime = 1.2,
		fireInterval = 0.6,
		projectileSpeed = 200,
		range = 500,
		splashRadius = 10,
		splashDamage = 25,
		magazineSize = 20,
		reserveAmmo = 60,
		reloadTime = 1.8,
		ammoPerShot = 5,
		tracerColor = Color3.fromRGB(255, 180, 50),
		muzzleFlashColor = Color3.fromRGB(255, 140, 30),
		weaponModel = "Plasma",
		recoil = 0.8,
		sprintSpeedMultiplier = 0.85,
	},

	-- === MELEE WEAPONS ===

	energy_sword = {
		id = "energy_sword",
		displayName = "Energy Sword",
		description = "Deadly melee. Lunging strike on click.",
		rarity = "Epic",
		behavior = "Melee",
		damage = 85,
		lungeDistance = 12,
		lungeDuration = 0.35,
		attackRange = 4,
		fireInterval = 0.6,
		lunging = false,
		tracerColor = Color3.fromRGB(255, 50, 50),
		muzzleFlashColor = Color3.fromRGB(255, 30, 30),
		weaponModel = "Sword",
		recoil = 0.2,
		sprintSpeedMultiplier = 1.0,
	},

	force_blade = {
		id = "force_blade",
		displayName = "Force Blade",
		description = "Melee weapon with wide arc and knockback.",
		rarity = "Rare",
		behavior = "MeleeSweep",
		damage = 55,
		sweepAngle = 120,
		attackRange = 4.5,
		knockbackForce = 40,
		fireInterval = 0.7,
		tracerColor = Color3.fromRGB(100, 200, 255),
		muzzleFlashColor = Color3.fromRGB(80, 170, 255),
		weaponModel = "Sword",
		recoil = 0.2,
		sprintSpeedMultiplier = 1.0,
	},

	-- === SPECIAL WEAPONS ===

	gravity_hammer = {
		id = "gravity_hammer",
		displayName = "Gravity Hammer",
		description = "Heavy melee that creates a gravity shockwave.",
		rarity = "Legendary",
		behavior = "MeleeExplosive",
		damage = 75,
		attackRange = 4,
		splashRadius = 12,
		splashDamage = 35,
		fireInterval = 1.0,
		knockbackForce = 60,
		gravityPulseRadius = 15,
		gravityPulseStrength = 8,
		tracerColor = Color3.fromRGB(200, 50, 255),
		muzzleFlashColor = Color3.fromRGB(180, 30, 230),
		weaponModel = "Hammer",
		recoil = 0.5,
		sprintSpeedMultiplier = 0.9,
	},

	flamethrower = {
		id = "flamethrower",
		displayName = "Flamethrower",
		description = "Continuous fire that ignites enemies in an area.",
		rarity = "Uncommon",
		behavior = "FlameThrower",
		damagePerSecond = 35,
		tickInterval = 0.15,
		range = 90,
		coneAngle = 50,
		burnDuration = 3,
		burnDamagePerTick = 12,
		burnTickInterval = 0.5,
		magazineSize = 150,
		reserveAmmo = 300,
		ammoDrainPerSecond = 25,
		reloadTime = 2.5,
		tracerColor = Color3.fromRGB(255, 120, 20),
		muzzleFlashColor = Color3.fromRGB(255, 80, 10),
		weaponModel = "Flamethrower",
		recoil = 0.2,
		sprintSpeedMultiplier = 0.9,
	},

	cryo_rifle = {
		id = "cryo_rifle",
		displayName = "Cryo Rifle",
		description = "Freezes enemies on hit, slowing them drastically.",
		rarity = "Epic",
		behavior = "HitscanAuto",
		damage = 12,
		headMultiplier = 1.5,
		fireInterval = 0.12,
		range = 350,
		spreadDegrees = 1.8,
		magazineSize = 25,
		reserveAmmo = 75,
		reloadTime = 1.6,
		slowMultiplier = 0.4,
		slowDuration = 2,
		freezeChance = 0.25,
		freezeDuration = 1.5,
		tracerColor = Color3.fromRGB(150, 220, 255),
		muzzleFlashColor = Color3.fromRGB(120, 200, 255),
		weaponModel = "Rifle",
		recoil = 0.5,
		sprintSpeedMultiplier = 0.88,
	},

	lightning_gun = {
		id = "lightning_gun",
		displayName = "Lightning Gun",
		description = "Chain lightning that jumps between nearby enemies.",
		rarity = "Legendary",
		behavior = "ChainLightning",
		damage = 45,
		chainRange = 25,
		maxChains = 4,
		chainDelay = 0.1,
		fireInterval = 0.8,
		range = 300,
		spreadDegrees = 0,
		magazineSize = 20,
		reserveAmmo = 60,
		reloadTime = 2.0,
		tracerColor = Color3.fromRGB(255, 255, 100),
		muzzleFlashColor = Color3.fromRGB(200, 200, 0),
		weaponModel = "Energy",
		recoil = 0.3,
		sprintSpeedMultiplier = 0.88,
	},
}

return WeaponConfig