--!strict

-- Pulse Deck Arena v2 - Weapon Configuration
-- 38 weapons across all behavior types

local WeaponConfig = {

	-- === ASSAULT WEAPONS (HitscanAuto) ===

	pulse_rifle = {
		id = "pulse_rifle",
		displayName = "Pulse Rifle",
		description = "Balanced automatic energy rifle. Reliable all-rounder.",
		rarity = "Common",
		behavior = "HitscanAuto",
		damage = 14,
		headMultiplier = 1.4,
		fireInterval = 0.105,
		range = 420,
		spreadDegrees = 1.6,
		magazineSize = 30,
		reserveAmmo = 90,
		reloadTime = 1.45,
		falloffStart = 150,
		falloffEnd = 360,
		falloffMultiplierAtEnd = 0.65,
		tracerColor = Color3.fromRGB(255, 230, 45),
		muzzleFlashColor = Color3.fromRGB(255, 200, 50),
		weaponModel = "Rifle",
		recoil = 0.8,
		sprintSpeedMultiplier = 0.85,
	},

	storm_rifle = {
		id = "storm_rifle",
		displayName = "Storm Rifle",
		description = "Rapid-fire energy rifle with lightning visuals.",
		rarity = "Uncommon",
		behavior = "HitscanAuto",
		damage = 11,
		headMultiplier = 1.35,
		fireInterval = 0.08,
		range = 380,
		spreadDegrees = 2.2,
		magazineSize = 40,
		reserveAmmo = 120,
		reloadTime = 1.6,
		falloffStart = 120,
		falloffEnd = 340,
		falloffMultiplierAtEnd = 0.6,
		tracerColor = Color3.fromRGB(180, 220, 255),
		muzzleFlashColor = Color3.fromRGB(150, 200, 255),
		weaponModel = "Rifle",
		recoil = 0.7,
		sprintSpeedMultiplier = 0.85,
	},

	plasma_rifle = {
		id = "plasma_rifle",
		displayName = "Plasma Rifle",
		description = "Fires superheated plasma bolts. Good range and damage.",
		rarity = "Uncommon",
		behavior = "HitscanAuto",
		damage = 18,
		headMultiplier = 1.5,
		fireInterval = 0.13,
		range = 450,
		spreadDegrees = 1.2,
		magazineSize = 24,
		reserveAmmo = 72,
		reloadTime = 1.8,
		falloffStart = 200,
		falloffEnd = 420,
		falloffMultiplierAtEnd = 0.7,
		tracerColor = Color3.fromRGB(255, 120, 40),
		muzzleFlashColor = Color3.fromRGB(255, 80, 20),
		weaponModel = "Rifle",
		recoil = 0.9,
		sprintSpeedMultiplier = 0.85,
	},

	titan_rifle = {
		id = "titan_rifle",
		displayName = "Titan Rifle",
		description = "Heavy assault rifle with armor-piercing rounds.",
		rarity = "Rare",
		behavior = "HitscanAuto",
		damage = 22,
		headMultiplier = 1.55,
		fireInterval = 0.16,
		range = 500,
		spreadDegrees = 1.0,
		magazineSize = 20,
		reserveAmmo = 60,
		reloadTime = 2.0,
		falloffStart = 250,
		falloffEnd = 480,
		falloffMultiplierAtEnd = 0.75,
		tracerColor = Color3.fromRGB(255, 60, 60),
		muzzleFlashColor = Color3.fromRGB(255, 30, 30),
		weaponModel = "Rifle",
		recoil = 1.2,
		sprintSpeedMultiplier = 0.8,
	},

	-- === SMGs (HitscanAuto fast fire) ===

	nano_smg = {
		id = "nano_smg",
		displayName = "Nano SMG",
		description = "Ultra-fast fire rate, low damage per shot. Spray and pray.",
		rarity = "Common",
		behavior = "HitscanAuto",
		damage = 8,
		headMultiplier = 1.25,
		fireInterval = 0.065,
		range = 260,
		spreadDegrees = 2.8,
		magazineSize = 42,
		reserveAmmo = 126,
		reloadTime = 1.55,
		falloffStart = 100,
		falloffEnd = 240,
		falloffMultiplierAtEnd = 0.7,
		tracerColor = Color3.fromRGB(95, 255, 180),
		muzzleFlashColor = Color3.fromRGB(80, 255, 160),
		weaponModel = "SMG",
		recoil = 0.4,
		sprintSpeedMultiplier = 0.9,
	},

	vortex_smg = {
		id = "vortex_smg",
		displayName = "Vortex SMG",
		description = "High-velocity SMG with piercing rounds.",
		rarity = "Uncommon",
		behavior = "HitscanAuto",
		damage = 10,
		headMultiplier = 1.3,
		fireInterval = 0.08,
		range = 320,
		spreadDegrees = 2.0,
		magazineSize = 36,
		reserveAmmo = 108,
		reloadTime = 1.5,
		falloffStart = 130,
		falloffEnd = 300,
		falloffMultiplierAtEnd = 0.72,
		pierceCount = 1,
		tracerColor = Color3.fromRGB(100, 200, 255),
		muzzleFlashColor = Color3.fromRGB(80, 180, 255),
		weaponModel = "SMG",
		recoil = 0.5,
		sprintSpeedMultiplier = 0.88,
	},

	shadow_smg = {
		id = "shadow_smg",
		displayName = "Shadow SMG",
		description = "Silenced SMG with stealth damage bonus.",
		rarity = "Rare",
		behavior = "HitscanAuto",
		damage = 12,
		headMultiplier = 1.5,
		fireInterval = 0.09,
		range = 280,
		spreadDegrees = 1.8,
		magazineSize = 32,
		reserveAmmo = 96,
		reloadTime = 1.6,
		falloffStart = 110,
		falloffEnd = 260,
		falloffMultiplierAtEnd = 0.7,
		stealthBonus = 1.4,
		tracerColor = Color3.fromRGB(200, 100, 255),
		muzzleFlashColor = Color3.fromRGB(150, 50, 200),
		weaponModel = "SMG",
		recoil = 0.3,
		sprintSpeedMultiplier = 0.92,
	},

	-- === SHOTGUNS ===

	scatter_cannon = {
		id = "scatter_cannon",
		displayName = "Scatter Cannon",
		description = "Close-range devastation. 8 pellets per shot.",
		rarity = "Common",
		behavior = "Shotgun",
		pellets = 8,
		damagePerPellet = 8,
		fireInterval = 0.78,
		range = 135,
		spreadDegrees = 7.5,
		magazineSize = 6,
		reserveAmmo = 30,
		reloadTime = 2.0,
		knockback = 35,
		tracerColor = Color3.fromRGB(255, 145, 40),
		muzzleFlashColor = Color3.fromRGB(255, 120, 30),
		weaponModel = "Shotgun",
		recoil = 1.5,
		sprintSpeedMultiplier = 0.9,
	},

	dual_blasters = {
		id = "dual_blasters",
		displayName = "Dual Blasters",
		description = "Twin rapid-fire blasters with wide spread.",
		rarity = "Uncommon",
		behavior = "Shotgun",
		pellets = 6,
		damagePerPellet = 10,
		fireInterval = 0.55,
		range = 120,
		spreadDegrees = 9.0,
		magazineSize = 12,
		reserveAmmo = 48,
		reloadTime = 1.8,
		knockback = 25,
		tracerColor = Color3.fromRGB(255, 200, 80),
		muzzleFlashColor = Color3.fromRGB(255, 180, 60),
		weaponModel = "Shotgun",
		recoil = 1.2,
		sprintSpeedMultiplier = 0.92,
	},

	pump_action = {
		id = "pump_action",
		displayName = "Pump Action",
		description = "Devastating single-shot shotgun. High damage, slow fire.",
		rarity = "Rare",
		behavior = "Shotgun",
		pellets = 12,
		damagePerPellet = 14,
		fireInterval = 1.2,
		range = 100,
		spreadDegrees = 5.0,
		magazineSize = 1,
		reserveAmmo = 8,
		reloadTime = 0.8,
		knockback = 60,
		headMultiplier = 2.0,
		tracerColor = Color3.fromRGB(255, 255, 100),
		muzzleFlashColor = Color3.fromRGB(255, 200, 50),
		weaponModel = "Shotgun",
		recoil = 2.5,
		sprintSpeedMultiplier = 0.85,
	},

	-- === SNIPERS (HitscanSniper) ===

	rail_lance = {
		id = "rail_lance",
		displayName = "Rail Lance",
		description = "Heavy sniper. Pierces through enemies.",
		rarity = "Rare",
		behavior = "HitscanSniper",
		damage = 82,
		headMultiplier = 1.6,
		fireInterval = 1.15,
		range = 800,
		spreadDegrees = 0.15,
		magazineSize = 5,
		reserveAmmo = 15,
		reloadTime = 2.25,
		pierceCount = 2,
		scopedFov = 38,
		unscopedFov = 70,
		tracerColor = Color3.fromRGB(170, 85, 255),
		muzzleFlashColor = Color3.fromRGB(140, 60, 230),
		weaponModel = "Sniper",
		recoil = 2.5,
		sprintSpeedMultiplier = 0.75,
	},

	longbow = {
		id = "longbow",
		displayName = "Longbow",
		description = "Precision sniper with guided arrow projectiles.",
		rarity = "Epic",
		behavior = "HitscanSniper",
		damage = 95,
		headMultiplier = 1.75,
		fireInterval = 1.5,
		range = 900,
		spreadDegrees = 0.1,
		magazineSize = 4,
		reserveAmmo = 12,
		reloadTime = 2.5,
		pierceCount = 1,
		guided = true,
		guidedTurnRate = 0.05,
		scopedFov = 35,
		unscopedFov = 70,
		tracerColor = Color3.fromRGB(50, 255, 100),
		muzzleFlashColor = Color3.fromRGB(30, 200, 80),
		weaponModel = "Sniper",
		recoil = 2.0,
		sprintSpeedMultiplier = 0.7,
	},

	hunter_rifle = {
		id = "hunter_rifle",
		displayName = "Hunter Rifle",
		description = "Quick-scope rifle with critical hit chance.",
		rarity = "Uncommon",
		behavior = "HitscanSniper",
		damage = 55,
		headMultiplier = 1.5,
		fireInterval = 0.65,
		range = 550,
		spreadDegrees = 0.3,
		magazineSize = 8,
		reserveAmmo = 32,
		reloadTime = 1.5,
		pierceCount = 0,
		critChance = 0.2,
		critMultiplier = 2.0,
		scopedFov = 45,
		unscopedFov = 70,
		tracerColor = Color3.fromRGB(255, 200, 50),
		muzzleFlashColor = Color3.fromRGB(255, 180, 30),
		weaponModel = "Sniper",
		recoil = 1.8,
		sprintSpeedMultiplier = 0.82,
	},

	-- === CHARGED SNIPER ===

	vortex_rifle = {
		id = "vortex_rifle",
		displayName = "Vortex Rifle",
		description = "Charged sniper shot that pulls enemies inward.",
		rarity = "Legendary",
		behavior = "ChargedSniper",
		baseDamage = 60,
		maxDamage = 130,
		chargeTime = 1.5,
		headMultiplier = 1.5,
		fireInterval = 1.8,
		range = 900,
		spreadDegrees = 0.1,
		magazineSize = 4,
		reserveAmmo = 12,
		reloadTime = 2.5,
		pierceCount = 1,
		scopedFov = 40,
		tracerColor = Color3.fromRGB(100, 200, 255),
		muzzleFlashColor = Color3.fromRGB(80, 180, 255),
		weaponModel = "Sniper",
		recoil = 2.0,
		sprintSpeedMultiplier = 0.78,
	},

	pulse_cannon = {
		id = "pulse_cannon",
		displayName = "Pulse Cannon",
		description = "Charge up for a massive energy blast.",
		rarity = "Legendary",
		behavior = "ChargedSniper",
		baseDamage = 80,
		maxDamage = 200,
		chargeTime = 2.0,
		headMultiplier = 1.8,
		fireInterval = 2.0,
		range = 850,
		spreadDegrees = 0.15,
		magazineSize = 3,
		reserveAmmo = 9,
		reloadTime = 3.0,
		pierceCount = 2,
		splashRadius = 8,
		splashDamage = 40,
		scopedFov = 35,
		tracerColor = Color3.fromRGB(255, 255, 100),
		muzzleFlashColor = Color3.fromRGB(255, 220, 50),
		weaponModel = "Sniper",
		recoil = 2.5,
		sprintSpeedMultiplier = 0.75,
	},

	-- === BURST FIRE ===

	phase_smg = {
		id = "phase_smg",
		displayName = "Phase SMG",
		description = "Burst-fire energy submachine gun.",
		rarity = "Uncommon",
		behavior = "BurstHitscan",
		damage = 9,
		headMultiplier = 1.25,
		burstCount = 3,
		burstInterval = 0.045,
		fireInterval = 0.24,
		range = 280,
		spreadDegrees = 2.2,
		magazineSize = 36,
		reserveAmmo = 108,
		reloadTime = 1.6,
		tracerColor = Color3.fromRGB(255, 50, 220),
		muzzleFlashColor = Color3.fromRGB(200, 30, 180),
		weaponModel = "SMG",
		recoil = 0.6,
		sprintSpeedMultiplier = 0.88,
	},

	quantum_burst = {
		id = "quantum_burst",
		displayName = "Quantum Burst",
		description = "3-round plasma burst with high accuracy.",
		rarity = "Rare",
		behavior = "BurstHitscan",
		damage = 14,
		headMultiplier = 1.4,
		burstCount = 3,
		burstInterval = 0.07,
		fireInterval = 0.35,
		range = 400,
		spreadDegrees = 1.0,
		magazineSize = 24,
		reserveAmmo = 72,
		reloadTime = 1.8,
		tracerColor = Color3.fromRGB(180, 255, 80),
		muzzleFlashColor = Color3.fromRGB(140, 220, 40),
		weaponModel = "Carbine",
		recoil = 0.8,
		sprintSpeedMultiplier = 0.88,
	},

	tri_beam = {
		id = "tri_beam",
		displayName = "Tri-Beam",
		description = "Triple laser burst, devastating at medium range.",
		rarity = "Epic",
		behavior = "BurstHitscan",
		damage = 22,
		headMultiplier = 1.5,
		burstCount = 3,
		burstInterval = 0.05,
		fireInterval = 0.55,
		range = 500,
		spreadDegrees = 0.8,
		magazineSize = 18,
		reserveAmmo = 54,
		reloadTime = 2.0,
		laserColor = Color3.fromRGB(255, 50, 50),
		tracerColor = Color3.fromRGB(255, 50, 50),
		muzzleFlashColor = Color3.fromRGB(255, 30, 30),
		weaponModel = "Beam",
		recoil = 1.0,
		sprintSpeedMultiplier = 0.85,
	},

	-- === SEMI-AUTO ===

	rivet_carbine = {
		id = "rivet_carbine",
		displayName = "Rivet Carbine",
		description = "Precise semi-auto with solid damage.",
		rarity = "Common",
		behavior = "SemiHitscan",
		damage = 21,
		headMultiplier = 1.35,
		fireInterval = 0.22,
		range = 390,
		spreadDegrees = 1.1,
		magazineSize = 18,
		reserveAmmo = 54,
		reloadTime = 1.75,
		tracerColor = Color3.fromRGB(40, 210, 200),
		muzzleFlashColor = Color3.fromRGB(30, 180, 170),
		weaponModel = "Carbine",
		recoil = 1.0,
		sprintSpeedMultiplier = 0.9,
	},

	auto_carbine = {
		id = "auto_carbine",
		displayName = "Auto Carbine",
		description = "Fast-firing carbine with moderate damage.",
		rarity = "Common",
		behavior = "HitscanAuto",
		damage = 12,
		headMultiplier = 1.3,
		fireInterval = 0.11,
		range = 340,
		spreadDegrees = 1.8,
		magazineSize = 28,
		reserveAmmo = 84,
		reloadTime = 1.5,
		falloffStart = 180,
		falloffEnd = 340,
		falloffMultiplierAtEnd = 0.7,
		tracerColor = Color3.fromRGB(100, 255, 150),
		muzzleFlashColor = Color3.fromRGB(70, 220, 130),
		weaponModel = "Carbine",
		recoil = 0.7,
		sprintSpeedMultiplier = 0.9,
	},

	needle_rifle = {
		id = "needle_rifle",
		displayName = "Needle Rifle",
		description = "Fires superheated needles with armor penetration.",
		rarity = "Uncommon",
		behavior = "SemiHitscan",
		damage = 26,
		headMultiplier = 1.5,
		fireInterval = 0.28,
		range = 460,
		spreadDegrees = 0.9,
		magazineSize = 12,
		reserveAmmo = 36,
		reloadTime = 1.3,
		armorPierce = 0.3,
		tracerColor = Color3.fromRGB(255, 200, 200),
		muzzleFlashColor = Color3.fromRGB(200, 170, 170),
		weaponModel = "Carbine",
		recoil = 1.1,
		sprintSpeedMultiplier = 0.88,
	},

	-- === PROJECTILE EXPLOSIVE ===

	arc_launcher = {
		id = "arc_launcher",
		displayName = "Arc Launcher",
		description = "Rocket launcher with devastating splash damage.",
		rarity = "Uncommon",
		behavior = "ProjectileExplosive",
		directDamage = 48,
		splashDamage = 42,
		splashRadius = 18,
		projectileSpeed = 175,
		fireInterval = 0.9,
		rangeLifetime = 4,
		magazineSize = 5,
		reserveAmmo = 15,
		reloadTime = 2.35,
		selfDamageMultiplier = 0.35,
		tracerColor = Color3.fromRGB(255, 90, 38),
		muzzleFlashColor = Color3.fromRGB(255, 70, 20),
		explosionEffect = true,
		weaponModel = "Launcher",
		recoil = 2.0,
		sprintSpeedMultiplier = 0.85,
	},

	bombard = {
		id = "bombard",
		displayName = "Bombard",
		description = "Heavy artillery launcher with huge AOE.",
		rarity = "Legendary",
		behavior = "ProjectileExplosive",
		directDamage = 85,
		splashDamage = 70,
		splashRadius = 28,
		projectileSpeed = 130,
		fireInterval = 1.8,
		rangeLifetime = 5,
		magazineSize = 3,
		reserveAmmo = 9,
		reloadTime = 3.5,
		selfDamageMultiplier = 0.5,
		tracerColor = Color3.fromRGB(255, 40, 40),
		muzzleFlashColor = Color3.fromRGB(255, 20, 20),
		explosionEffect = true,
		weaponModel = "Launcher",
		recoil = 3.0,
		sprintSpeedMultiplier = 0.7,
	},

	proximity_mine = {
		id = "proximity_mine",
		displayName = "Proximity Mine",
		description = "Sticky mine that detonates when enemies approach.",
		rarity = "Uncommon",
		behavior = "StickyGrenade",
		directDamage = 60,
		splashDamage = 40,
		splashRadius = 12,
		fireInterval = 0.8,
		magazineSize = 3,
		reserveAmmo = 9,
		reloadTime = 1.5,
		fuseTime = 0.5,
		burnDuration = 3,
		burnDamagePerTick = 10,
		burnTickInterval = 0.3,
		stickRadius = 5,
		proximityRadius = 8,
		tracerColor = Color3.fromRGB(255, 80, 40),
		muzzleFlashColor = Color3.fromRGB(255, 50, 20),
		weaponModel = "GrenadeLauncher",
		recoil = 0.5,
		sprintSpeedMultiplier = 0.92,
	},

	frag_grenade = {
		id = "frag_grenade",
		displayName = "Frag Grenade",
		description = "Bouncing frag grenade with delayed fuse.",
		rarity = "Common",
		behavior = "ProjectileExplosive",
		directDamage = 15,
		splashDamage = 45,
		splashRadius = 15,
		projectileSpeed = 90,
		fireInterval = 1.2,
		rangeLifetime = 2.5,
		magazineSize = 2,
		reserveAmmo = 6,
		reloadTime = 1.8,
		selfDamageMultiplier = 0.15,
		bouncy = true,
		bounceCount = 3,
		fuseTime = 1.5,
		tracerColor = Color3.fromRGB(200, 200, 50),
		muzzleFlashColor = Color3.fromRGB(180, 180, 30),
		explosionEffect = true,
		weaponModel = "GrenadeLauncher",
		recoil = 0.5,
		sprintSpeedMultiplier = 0.95,
	},

	-- === CLUSTER/MORTAR ===

	cluster_mortar = {
		id = "cluster_mortar",
		displayName = "Cluster Mortar",
		description = "High-arcing mortar that splits into bomblets.",
		rarity = "Rare",
		behavior = "ProjectileCluster",
		directDamage = 35,
		splashDamage = 28,
		splashRadius = 14,
		projectileSpeed = 120,
		arcHeight = 40,
		fireInterval = 1.4,
		rangeLifetime = 3.5,
		magazineSize = 4,
		reserveAmmo = 12,
		reloadTime = 2.8,
		selfDamageMultiplier = 0.2,
		subMunitions = 6,
		subDamage = 12,
		subRadius = 7,
		tracerColor = Color3.fromRGB(200, 120, 40),
		muzzleFlashColor = Color3.fromRGB(180, 90, 20),
		weaponModel = "Mortar",
		recoil = 1.5,
		sprintSpeedMultiplier = 0.85,
	},

	incendiary_mortar = {
		id = "incendiary_mortar",
		displayName = "Incendiary Mortar",
		description = "Fire mortar that leaves a burning zone.",
		rarity = "Rare",
		behavior = "ProjectileCluster",
		directDamage = 30,
		splashDamage = 35,
		splashRadius = 16,
		projectileSpeed = 100,
		arcHeight = 45,
		fireInterval = 1.8,
		rangeLifetime = 4,
		magazineSize = 3,
		reserveAmmo = 9,
		reloadTime = 3.0,
		burnDuration = 6,
		burnDamagePerTick = 15,
		burnTickInterval = 0.5,
		selfDamageMultiplier = 0.25,
		subMunitions = 4,
		subDamage = 10,
		subRadius = 10,
		tracerColor = Color3.fromRGB(255, 100, 20),
		muzzleFlashColor = Color3.fromRGB(255, 60, 10),
		weaponModel = "Mortar",
		recoil = 1.3,
		sprintSpeedMultiplier = 0.85,
	},

	-- === ENERGY WEAPONS (Beam) ===

	ion_beam = {
		id = "ion_beam",
		displayName = "Ion Beam",
		description = "Continuous beam that drains ammo over time.",
		rarity = "Rare",
		behavior = "Beam",
		damagePerSecond = 52,
		tickInterval = 0.1,
		range = 190,
		beamWidth = 2.5,
		magazineSize = 100,
		ammoDrainPerSecond = 18,
		reloadTime = 1.9,
		tracerColor = Color3.fromRGB(60, 235, 255),
		muzzleFlashColor = Color3.fromRGB(40, 220, 255),
		weaponModel = "Beam",
		recoil = 0.3,
		sprintSpeedMultiplier = 0.8,
	},

	disruptor_beam = {
		id = "disruptor_beam",
		displayName = "Disruptor Beam",
		description = "Beam that slows and weakens enemies.",
		rarity = "Uncommon",
		behavior = "Beam",
		damagePerSecond = 28,
		tickInterval = 0.1,
		range = 170,
		beamWidth = 2.0,
		magazineSize = 80,
		ammoDrainPerSecond = 14,
		reloadTime = 1.6,
		slowAmount = 0.6,
		tracerColor = Color3.fromRGB(80, 255, 180),
		muzzleFlashColor = Color3.fromRGB(50, 220, 150),
		weaponModel = "Beam",
		recoil = 0.2,
		sprintSpeedMultiplier = 0.85,
	},

	-- === SPECIAL WEAPONS ===

	gravity_hammer = {
		id = "gravity_hammer",
		displayName = "Gravity Hammer",
		description = "Heavy melee that creates a gravity shockwave.",
		rarity = "Legendary",
		behavior = "MeleeExplosive",
		damage = 75,
		attackRange = 4,
		splashRadius = 12,
		splashDamage = 35,
		fireInterval = 1.0,
		knockbackForce = 60,
		gravityPulseRadius = 15,
		gravityPulseStrength = 8,
		tracerColor = Color3.fromRGB(200, 50, 255),
		muzzleFlashColor = Color3.fromRGB(180, 30, 230),
		weaponModel = "Hammer",
		recoil = 0.5,
		sprintSpeedMultiplier = 0.9,
	},

	force_blade = {
		id = "force_blade",
		displayName = "Force Blade",
		description = "Melee weapon with wide arc and knockback.",
		rarity = "Rare",
		behavior = "MeleeSweep",
		damage = 55,
		sweepAngle = 120,
		attackRange = 4.5,
		knockbackForce = 40,
		fireInterval = 0.7,
		tracerColor = Color3.fromRGB(100, 200, 255),
		muzzleFlashColor = Color3.fromRGB(80, 170, 255),
		weaponModel = "Sword",
		recoil = 0.2,
		sprintSpeedMultiplier = 1.0,
	},

	energy_sword = {
		id = "energy_sword",
		displayName = "Energy Sword",
		description = "Deadly melee. Lunging strike on click.",
		rarity = "Epic",
		behavior = "Melee",
		damage = 85,
		lungeDistance = 12,
		lungeDuration = 0.35,
		attackRange = 4,
		fireInterval = 0.6,
		tracerColor = Color3.fromRGB(255, 50, 50),
		muzzleFlashColor = Color3.fromRGB(255, 30, 30),
		weaponModel = "Sword",
		recoil = 0.2,
		sprintSpeedMultiplier = 1.0,
	},

	chain_saw = {
		id = "chain_saw",
		displayName = "Chain Saw",
		description = "Devastating continuous melee damage.",
		rarity = "Epic",
		behavior = "MeleeSweep",
		damage = 35,
		damagePerSecond = 80,
		sweepAngle = 180,
		attackRange = 3.5,
		tickInterval = 0.08,
		fireInterval = 0.6,
		knockbackForce = 30,
		tracerColor = Color3.fromRGB(255, 150, 30),
		muzzleFlashColor = Color3.fromRGB(255, 100, 20),
		weaponModel = "Hammer",
		recoil = 0.6,
		sprintSpeedMultiplier = 0.95,
	},

	-- === FLAMETHROWER ===

	flamethrower = {
		id = "flamethrower",
		displayName = "Flamethrower",
		description = "Continuous fire that ignites enemies in an area.",
		rarity = "Uncommon",
		behavior = "FlameThrower",
		damagePerSecond = 35,
		tickInterval = 0.15,
		range = 90,
		coneAngle = 50,
		burnDuration = 3,
		burnDamagePerTick = 12,
		burnTickInterval = 0.5,
		magazineSize = 150,
		reserveAmmo = 300,
		reloadTime = 2.5,
		ammoDrainPerSecond = 25,
		tracerColor = Color3.fromRGB(255, 120, 20),
		muzzleFlashColor = Color3.fromRGB(255, 80, 10),
		weaponModel = "Flamethrower",
		recoil = 0.2,
		sprintSpeedMultiplier = 0.9,
	},

	cryo_rifle = {
		id = "cryo_rifle",
		displayName = "Cryo Rifle",
		description = "Freezes enemies on hit, slowing them drastically.",
		rarity = "Epic",
		behavior = "HitscanAuto",
		damage = 12,
		headMultiplier = 1.5,
		fireInterval = 0.12,
		range = 350,
		spreadDegrees = 1.8,
		magazineSize = 25,
		reserveAmmo = 75,
		reloadTime = 1.6,
		slowMultiplier = 0.4,
		slowDuration = 2,
		freezeChance = 0.25,
		freezeDuration = 1.5,
		tracerColor = Color3.fromRGB(150, 220, 255),
		muzzleFlashColor = Color3.fromRGB(120, 200, 255),
		weaponModel = "Rifle",
		recoil = 0.5,
		sprintSpeedMultiplier = 0.88,
	},

	lightning_gun = {
		id = "lightning_gun",
		displayName = "Lightning Gun",
		description = "Chain lightning that jumps between nearby enemies.",
		rarity = "Legendary",
		behavior = "ChainLightning",
		damage = 45,
		chainRange = 25,
		maxChains = 4,
		chainDelay = 0.1,
		fireInterval = 0.8,
		range = 300,
		spreadDegrees = 0,
		magazineSize = 20,
		reserveAmmo = 60,
		reloadTime = 2.0,
		tracerColor = Color3.fromRGB(255, 255, 100),
		muzzleFlashColor = Color3.fromRGB(200, 200, 0),
		weaponModel = "Energy",
		recoil = 0.3,
		sprintSpeedMultiplier = 0.88,
	},

	-- === BURST HITSCAN (new) ===

	thunder_burst = {
		id = "thunder_burst",
		displayName = "Thunder Burst",
		description = "3-shot burst with lightning chain reaction.",
		rarity = "Epic",
		behavior = "BurstHitscan",
		damage = 18,
		headMultiplier = 1.5,
		burstCount = 3,
		burstInterval = 0.06,
		fireInterval = 0.45,
		range = 420,
		spreadDegrees = 1.2,
		magazineSize = 24,
		reserveAmmo = 72,
		reloadTime = 1.9,
		chainLightning = true,
		chainRange = 15,
		maxChainsOnBurst = 2,
		tracerColor = Color3.fromRGB(255, 220, 80),
		muzzleFlashColor = Color3.fromRGB(255, 180, 40),
		weaponModel = "Carbine",
		recoil = 0.9,
		sprintSpeedMultiplier = 0.88,
	},

	-- === CHARGED PROJECTILE (new) ===

	nova_launcher = {
		id = "nova_launcher",
		displayName = "Nova Launcher",
		description = "Charges up an explosive plasma orb.",
		rarity = "Legendary",
		behavior = "ChargingProjectile",
		minDamage = 30,
		maxDamage = 95,
		chargeTime = 2.0,
		fireInterval = 0.8,
		projectileSpeed = 180,
		range = 550,
		splashRadius = 15,
		splashDamage = 40,
		magazineSize = 6,
		reserveAmmo = 18,
		reloadTime = 2.2,
		ammoPerShot = 4,
		tracerColor = Color3.fromRGB(255, 100, 200),
		muzzleFlashColor = Color3.fromRGB(200, 50, 150),
		weaponModel = "Plasma",
		recoil = 1.2,
		sprintSpeedMultiplier = 0.82,
	},

	-- === STICKY GRENADE (new) ===

	sticky_bomb = {
		id = "sticky_bomb",
		displayName = "Sticky Bomb",
		description = "High-explosive that sticks to any surface.",
		rarity = "Rare",
		behavior = "StickyGrenade",
		directDamage = 70,
		splashDamage = 55,
		splashRadius = 16,
		fireInterval = 0.8,
		magazineSize = 2,
		reserveAmmo = 8,
		reloadTime = 1.8,
		fuseTime = 2.5,
		armTime = 0.5,
		selfDamageMultiplier = 0.2,
		tracerColor = Color3.fromRGB(255, 200, 50),
		muzzleFlashColor = Color3.fromRGB(255, 150, 20),
		weaponModel = "GrenadeLauncher",
		recoil = 0.8,
		sprintSpeedMultiplier = 0.92,
	},

	-- === BFG-STYLE (new) ===

	hellfire_cannon = {
		id = "hellfire_cannon",
		displayName = "Hellfire Cannon",
		description = "Slow but devastating projectile with massive AOE.",
		rarity = "Legendary",
		behavior = "ProjectileExplosive",
		directDamage = 120,
		splashDamage = 80,
		splashRadius = 30,
		projectileSpeed = 80,
		fireInterval = 2.5,
		rangeLifetime = 4,
		magazineSize = 2,
		reserveAmmo = 4,
		reloadTime = 4.0,
		selfDamageMultiplier = 0.6,
		tracerColor = Color3.fromRGB(255, 30, 30),
		muzzleFlashColor = Color3.fromRGB(255, 10, 10),
		explosionEffect = true,
		weaponModel = "Launcher",
		recoil = 3.5,
		sprintSpeedMultiplier = 0.6,
	},

	-- === RAPID SNIPER (new) ===

	storm_sniper = {
		id = "storm_sniper",
		displayName = "Storm Sniper",
		description = "Semi-auto sniper with fire rate upgrade.",
		rarity = "Rare",
		behavior = "HitscanSniper",
		damage = 65,
		headMultiplier = 1.7,
		fireInterval = 0.45,
		range = 700,
		spreadDegrees = 0.2,
		magazineSize = 10,
		reserveAmmo = 40,
		reloadTime = 1.6,
		pierceCount = 1,
		scopedFov = 40,
		unscopedFov = 70,
		tracerColor = Color3.fromRGB(130, 180, 255),
		muzzleFlashColor = Color3.fromRGB(100, 150, 255),
		weaponModel = "Sniper",
		recoil = 1.8,
		sprintSpeedMultiplier = 0.78,
	},

	-- === MELEE: AXE (new) ===

	plasma_axe = {
		id = "plasma_axe",
		displayName = "Plasma Axe",
		description = "Swing AoE plasma arc in a wide cleave.",
		rarity = "Epic",
		behavior = "MeleeSweep",
		damage = 60,
		sweepAngle = 150,
		attackRange = 5,
		knockbackForce = 35,
		fireInterval = 0.8,
		burnDamage = 15,
		burnDuration = 2,
		tracerColor = Color3.fromRGB(255, 150, 50),
		muzzleFlashColor = Color3.fromRGB(255, 100, 30),
		weaponModel = "Hammer",
		recoil = 0.4,
		sprintSpeedMultiplier = 0.95,
	},

	-- === SHOTGUN: AUTO (new) ===

	auto_shotgun = {
		id = "auto_shotgun",
		displayName = "Auto Shotgun",
		description = "Automatic shotgun with rapid follow-up.",
		rarity = "Rare",
		behavior = "Shotgun",
		pellets = 10,
		damagePerPellet = 7,
		fireInterval = 0.35,
		range = 115,
		spreadDegrees = 8.0,
		magazineSize = 15,
		reserveAmmo = 60,
		reloadTime = 2.2,
		knockback = 20,
		tracerColor = Color3.fromRGB(200, 180, 50),
		muzzleFlashColor = Color3.fromRGB(180, 140, 30),
		weaponModel = "Shotgun",
		recoil = 1.0,
		sprintSpeedMultiplier = 0.88,
	},

	-- === SHOTGUN: HEAVY (new) ===

	riot_shotgun = {
		id = "riot_shotgun",
		displayName = "Riot Shotgun",
		description = "Wide-spread crowd control shotgun.",
		rarity = "Common",
		behavior = "Shotgun",
		pellets = 12,
		damagePerPellet = 5,
		fireInterval = 0.9,
		range = 100,
		spreadDegrees = 10.0,
		magazineSize = 8,
		reserveAmmo = 32,
		reloadTime = 1.6,
		knockback = 45,
		tracerColor = Color3.fromRGB(180, 220, 100),
		muzzleFlashColor = Color3.fromRGB(150, 200, 60),
		weaponModel = "Shotgun",
		recoil = 1.3,
		sprintSpeedMultiplier = 0.88,
	},

	-- === PLASMA SPLASH (new - ChargingProjectile) ===

	plasma_orb = {
		id = "plasma_orb",
		displayName = "Plasma Orb",
		description = "Charge and lob a bouncing plasma orb.",
		rarity = "Epic",
		behavior = "ChargingProjectile",
		minDamage = 15,
		maxDamage = 55,
		chargeTime = 1.5,
		fireInterval = 0.7,
		projectileSpeed = 140,
		range = 400,
		splashRadius = 12,
		splashDamage = 25,
		magazineSize = 8,
		reserveAmmo = 24,
		reloadTime = 1.5,
		ammoPerShot = 3,
		bouncy = true,
		bounceCount = 2,
		tracerColor = Color3.fromRGB(180, 80, 255),
		muzzleFlashColor = Color3.fromRGB(140, 50, 220),
		weaponModel = "Plasma",
		recoil = 0.9,
		sprintSpeedMultiplier = 0.85,
	},

	-- === RAILGUN-STYLE (new - HitscanSniper extreme) ===

	particle_beam = {
		id = "particle_beam",
		displayName = "Particle Beam",
		description = "Ultra-piercing beam that hits everything in a line.",
		rarity = "Legendary",
		behavior = "HitscanSniper",
		damage = 150,
		headMultiplier = 1.3,
		fireInterval = 2.5,
		range = 2000,
		spreadDegrees = 0.0,
		magazineSize = 6,
		reserveAmmo = 18,
		reloadTime = 3.0,
		pierceCount = 99,
		scopedFov = 25,
		unscopedFov = 70,
		tracerColor = Color3.fromRGB(255, 255, 255),
		muzzleFlashColor = Color3.fromRGB(255, 255, 200),
		weaponModel = "Sniper",
		recoil = 3.0,
		sprintSpeedMultiplier = 0.65,
	},

	-- === DUAL WIELD (new - fast auto) ===

	twin_pistols = {
		id = "twin_pistols",
		displayName = "Twin Pistols",
		description = "Dual wield with double the fire rate.",
		rarity = "Uncommon",
		behavior = "HitscanAuto",
		damage = 9,
		headMultiplier = 1.3,
		fireInterval = 0.05,
		range = 280,
		spreadDegrees = 3.0,
		magazineSize = 30,
		reserveAmmo = 90,
		reloadTime = 1.2,
		falloffStart = 80,
		falloffEnd = 240,
		falloffMultiplierAtEnd = 0.75,
		dualWield = true,
		tracerColor = Color3.fromRGB(255, 255, 150),
		muzzleFlashColor = Color3.fromRGB(255, 220, 100),
		weaponModel = "SMG",
		recoil = 0.6,
		sprintSpeedMultiplier = 0.92,
	},

	-- === GRENADE LAUNCHER (new) ===

	grenade_launcher = {
		id = "grenade_launcher",
		displayName = "Grenade Launcher",
		description = "Launches bouncing grenades with timed fuse.",
		rarity = "Uncommon",
		behavior = "ProjectileExplosive",
		directDamage = 20,
		splashDamage = 40,
		splashRadius = 14,
		projectileSpeed = 110,
		fireInterval = 1.0,
		rangeLifetime = 3,
		magazineSize = 4,
		reserveAmmo = 16,
		reloadTime = 2.0,
		selfDamageMultiplier = 0.1,
		bouncy = true,
		bounceCount = 2,
		fuseTime = 1.2,
		tracerColor = Color3.fromRGB(200, 200, 80),
		muzzleFlashColor = Color3.fromRGB(180, 180, 50),
		explosionEffect = true,
		weaponModel = "GrenadeLauncher",
		recoil = 1.2,
		sprintSpeedMultiplier = 0.9,
	},

	-- === FLAMETHROWER HEAVY (new) ===

	plasma_flamer = {
		id = "plasma_flamer",
		displayName = "Plasma Flamer",
		description = "Superheated plasma in a wide cone.",
		rarity = "Rare",
		behavior = "FlameThrower",
		damagePerSecond = 55,
		tickInterval = 0.1,
		range = 80,
		coneAngle = 60,
		burnDuration = 4,
		burnDamagePerTick = 18,
		burnTickInterval = 0.3,
		magazineSize = 120,
		reserveAmmo = 240,
		reloadTime = 2.8,
		ammoDrainPerSecond = 30,
		tracerColor = Color3.fromRGB(255, 100, 255),
		muzzleFlashColor = Color3.fromRGB(200, 50, 200),
		weaponModel = "Flamethrower",
		recoil = 0.3,
		sprintSpeedMultiplier = 0.88,
	},

	-- === MINIGUN-STYLE (new - HitscanAuto extreme fire rate) ===

	neutron_blaster = {
		id = "neutron_blaster",
		displayName = "Neutron Blaster",
		description = "Insanely fast energy weapon. Low per-shot, extreme DPS.",
		rarity = "Legendary",
		behavior = "HitscanAuto",
		damage = 6,
		headMultiplier = 1.8,
		fireInterval = 0.035,
		range = 380,
		spreadDegrees = 3.5,
		magazineSize = 200,
		reserveAmmo = 400,
		reloadTime = 3.5,
		falloffStart = 150,
		falloffEnd = 350,
		falloffMultiplierAtEnd = 0.6,
		tracerColor = Color3.fromRGB(200, 255, 200),
		muzzleFlashColor = Color3.fromRGB(150, 255, 150),
		weaponModel = "SMG",
		recoil = 0.3,
		sprintSpeedMultiplier = 0.75,
	},

	-- === ENERGY SCATTER (new) ===

	scatter_blaster = {
		id = "scatter_blaster",
		displayName = "Scatter Blaster",
		description = "Energy shotgun with wide arc.",
		rarity = "Uncommon",
		behavior = "Shotgun",
		pellets = 14,
		damagePerPellet = 6,
		fireInterval = 0.6,
		range = 110,
		spreadDegrees = 10.0,
		magazineSize = 10,
		reserveAmmo = 40,
		reloadTime = 1.7,
		knockback = 30,
		tracerColor = Color3.fromRGB(150, 100, 255),
		muzzleFlashColor = Color3.fromRGB(120, 60, 220),
		weaponModel = "Shotgun",
		recoil = 1.4,
		sprintSpeedMultiplier = 0.88,
	},

	-- === THROWING (new - Projectile with bounce) ===

	energy_disc = {
		id = "energy_disc",
		displayName = "Energy Disc",
		description = "Ricocheting energy disc.",
		rarity = "Epic",
		behavior = "ProjectileExplosive",
		directDamage = 40,
		splashDamage = 20,
		splashRadius = 8,
		projectileSpeed = 250,
		fireInterval = 0.5,
		rangeLifetime = 2,
		magazineSize = 10,
		reserveAmmo = 30,
		reloadTime = 1.2,
		selfDamageMultiplier = 0.05,
		bouncy = true,
		bounceCount = 5,
		tracerColor = Color3.fromRGB(50, 200, 255),
		muzzleFlashColor = Color3.fromRGB(30, 160, 220),
		weaponModel = "Energy",
		recoil = 0.3,
		sprintSpeedMultiplier = 0.92,
	},

	-- === FREEZE RAY (new) ===

	freeze_ray = {
		id = "freeze_ray",
		displayName = "Freeze Ray",
		description = "Continuous beam that freezes enemies solid.",
		rarity = "Epic",
		behavior = "Beam",
		damagePerSecond = 20,
		tickInterval = 0.1,
		range = 160,
		beamWidth = 2.0,
		magazineSize = 80,
		ammoDrainPerSecond = 15,
		reloadTime = 1.8,
		freezeChance = 0.4,
		freezeDuration = 2.5,
		slowMultiplier = 0.3,
		tracerColor = Color3.fromRGB(100, 220, 255),
		muzzleFlashColor = Color3.fromRGB(80, 200, 255),
		weaponModel = "Beam",
		recoil = 0.2,
		sprintSpeedMultiplier = 0.85,
	},

	-- === HEALING RIFLE (new - support hybrid) ===

	bio_rifle = {
		id = "bio_rifle",
		displayName = "Bio Rifle",
		description = "Heals allies and poisons enemies.",
		rarity = "Rare",
		behavior = "HitscanAuto",
		damage = 10,
		headMultiplier = 1.3,
		fireInterval = 0.12,
		range = 300,
		spreadDegrees = 1.5,
		magazineSize = 30,
		reserveAmmo = 90,
		reloadTime = 1.6,
		falloffStart = 150,
		falloffEnd = 280,
		falloffMultiplierAtEnd = 0.7,
		healingPerShot = 5,
		poisonDamage = 3,
		poisonDuration = 3,
		tracerColor = Color3.fromRGB(100, 255, 100),
		muzzleFlashColor = Color3.fromRGB(80, 220, 80),
		weaponModel = "Rifle",
		recoil = 0.5,
		sprintSpeedMultiplier = 0.88,
	},
}

return WeaponConfig